import { Injectable, NotFoundException, ForbiddenException, Logger } from '@nestjs/common';
import { PrismaService } from '../prisma/prisma.service';
import { LlmProvidersService } from '../llm-providers/llm-providers.service';
import { CreateEntryDto, ReviewEntryDto, InsightProfileDto } from './dto';
import { buildIdentityLayer } from '../consult/orchestrator/prompt-layers';

@Injectable()
export class ChronicleService {
  private readonly logger = new Logger(ChronicleService.name);
  constructor(
    private readonly prisma: PrismaService,
    private readonly llmProviders: LlmProvidersService,
  ) {}

  // ========== 记录管理 ==========

  async createEntry(dto: CreateEntryDto) {
    return this.prisma.chronicleEntry.create({
      data: {
        userId: dto.userId || null,
        consultRecordId: dto.consultRecordId || null,
        personId: dto.personId || null,
        title: dto.title,
        content: dto.content,
        entryType: dto.entryType || 'case',
      },
    });
  }

  async findByUser(userId: string) {
    return this.prisma.chronicleEntry.findMany({
      where: { userId },
      orderBy: { createdAt: 'desc' },
    });
  }

  async findByType(userId: string, entryType: string) {
    return this.prisma.chronicleEntry.findMany({
      where: { userId, entryType },
      orderBy: { createdAt: 'desc' },
    });
  }

  async getPendingReviews(userId: string) {
    return this.prisma.chronicleEntry.findMany({
      where: {
        userId,
        reviewAt: { lte: new Date() },
        reviewedAt: null,
      },
      orderBy: { reviewAt: 'asc' },
    });
  }

  // ========== 回看验证 ==========

  async addReview(entryId: string, dto: ReviewEntryDto, userId: string) {  // P0-4 新增 userId
    const entry = await this.prisma.chronicleEntry.findUnique({
      where: { id: entryId },
    });
    if (!entry) throw new NotFoundException('Entry not found');

    // P0-4 所有权校验
    if (entry.userId !== userId) {
      this.logger.warn(`[P0-4-AUDIT] addReview forbidden: entryId=${entryId} caller=${userId} owner=${entry.userId}`);
      throw new ForbiddenException('无权访问该记录');
    }

    return this.prisma.chronicleEntry.update({
      where: { id: entryId },
      data: {
        initialView: dto.initialView,
        whatHappened: dto.whatHappened,
        gotRight: dto.gotRight,
        gotWrong: dto.gotWrong,
        nextReminder: dto.nextReminder,
        reviewAt: dto.reviewAt,
        reviewedAt: new Date(),
      },
    });
  }

  // ========== 用户画像 ==========

  async generateInsightProfile(userId: string): Promise<InsightProfileDto> {
    const entries = await this.prisma.chronicleEntry.findMany({
      where: { userId },
      orderBy: { createdAt: 'desc' },
    });

    const reviewedEntries = entries.filter((e) => e.reviewedAt);

    if (entries.length === 0) {
      return {
        commonStuckPoints: [],
        riskPreference: '未知',
        relationshipHabits: [],
        misjudgmentPatterns: [],
        commonTriggers: [],
        longTermTrend: '数据不足',
        totalEntries: 0,
        totalReviews: 0,
      };
    }

    // 调用 LLM 生成洞察
    const insight = await this.generateInsightWithLLM(entries);

    // 更新或创建用户画像
    await this.prisma.userInsightProfile.upsert({
      where: { userId },
      create: {
        userId,
        commonStuckPoints: JSON.stringify(insight.commonStuckPoints),
        riskPreference: insight.riskPreference,
        relationshipHabits: JSON.stringify(insight.relationshipHabits),
        misjudgmentPatterns: JSON.stringify(insight.misjudgmentPatterns),
        commonTriggers: JSON.stringify(insight.commonTriggers),
        longTermTrend: insight.longTermTrend,
        totalEntries: entries.length,
        totalReviews: reviewedEntries.length,
        autoGenerated: true,
        generatedAt: new Date(),
      },
      update: {
        commonStuckPoints: JSON.stringify(insight.commonStuckPoints),
        riskPreference: insight.riskPreference,
        relationshipHabits: JSON.stringify(insight.relationshipHabits),
        misjudgmentPatterns: JSON.stringify(insight.misjudgmentPatterns),
        commonTriggers: JSON.stringify(insight.commonTriggers),
        longTermTrend: insight.longTermTrend,
        totalEntries: entries.length,
        totalReviews: reviewedEntries.length,
        autoGenerated: true,
        generatedAt: new Date(),
      },
    });

    return {
      ...insight,
      totalEntries: entries.length,
      totalReviews: reviewedEntries.length,
      accuracyRate: reviewedEntries.length > 0
        ? reviewedEntries.filter((e) => e.gotRight && e.gotRight.length > 0).length /
          reviewedEntries.length
        : undefined,
    };
  }

  async getInsightProfile(userId: string): Promise<InsightProfileDto | null> {
    const profile = await this.prisma.userInsightProfile.findUnique({
      where: { userId },
    });
    if (!profile) return null;

    return {
      commonStuckPoints: JSON.parse(profile.commonStuckPoints || '[]'),
      riskPreference: profile.riskPreference || '未知',
      relationshipHabits: JSON.parse(profile.relationshipHabits || '[]'),
      misjudgmentPatterns: JSON.parse(profile.misjudgmentPatterns || '[]'),
      commonTriggers: JSON.parse(profile.commonTriggers || '[]'),
      longTermTrend: profile.longTermTrend || '',
      totalEntries: profile.totalEntries,
      totalReviews: profile.totalReviews,
      accuracyRate: profile.accuracyRate || undefined,
    };
  }

  private async generateInsightWithLLM(
    entries: any[],
  ): Promise<Omit<InsightProfileDto, 'totalEntries' | 'totalReviews' | 'accuracyRate'>> {
    const entriesText = entries
      .map(
        (e) =>
          `- ${e.title}: ${e.content.slice(0, 100)}${e.initialView ? ` (回看: ${e.initialView})` : ''}`,
      )
      .join('\n');

    const prompt = `基于以下用户的决策记录，生成个人洞察画像：

记录：
${entriesText}

请用 JSON 格式返回：
- commonStuckPoints: 常见卡点列表
- riskPreference: 风险偏好（保守/平衡/激进）
- relationshipHabits: 关系判断习惯
- misjudgmentPatterns: 常见误判模式
- commonTriggers: 容易上头的场景
- longTermTrend: 长期变化趋势总结

只返回 JSON，不要其他内容。`;

    try {
      const response = await this.llmProviders.chatCheap(
        [
          { role: 'system', content: buildIdentityLayer() + '\n\n你是一位行为分析专家，擅长从决策记录中提取模式和洞察。' },
          { role: 'user', content: prompt },
        ],
        { temperature: 0.4, jsonMode: true },
      );

      const result = JSON.parse(this.extractJson(response.content));
      return {
        commonStuckPoints: result.commonStuckPoints || [],
        riskPreference: result.riskPreference || '未知',
        relationshipHabits: result.relationshipHabits || [],
        misjudgmentPatterns: result.misjudgmentPatterns || [],
        commonTriggers: result.commonTriggers || [],
        longTermTrend: result.longTermTrend || '',
      };
    } catch (error) {
      return {
        commonStuckPoints: [],
        riskPreference: '未知',
        relationshipHabits: [],
        misjudgmentPatterns: [],
        commonTriggers: [],
        longTermTrend: '数据不足',
      };
    }
  }

  private extractJson(text: string): string {
    const match = text.match(/\{[\s\S]*\}/);
    return match ? match[0] : '{}';
  }
}
