import type { KlineRuleFactor, KlineAspect } from './types';

export const KLINE_RULE_FACTORS: KlineRuleFactor[] = [
  {
    sourceId: 'ZP-WEALTH-001',
    title: '食伤生财',
    appliesTo: ['wealth'],
    direction: 'positive',
    weight: 12,
    volatility: 8,
    confidence: 80,
    evidenceTag: '食伤生财',
    explanation: '食伤为财之源，食伤生财时财运机会增多',
  },
  {
    sourceId: 'ZP-WEALTH-002',
    title: '比劫夺财',
    appliesTo: ['wealth'],
    direction: 'negative',
    weight: -10,
    volatility: 12,
    confidence: 75,
    evidenceTag: '比劫夺财',
    explanation: '比劫多则竞争加剧，该进财时容易被分走',
  },
  {
    sourceId: 'ZP-WEALTH-003',
    title: '财星透出',
    appliesTo: ['wealth'],
    direction: 'positive',
    weight: 10,
    volatility: 6,
    confidence: 85,
    evidenceTag: '财星透出',
    explanation: '财星透干主外财显现，适合主动出击',
  },
  {
    sourceId: 'ZP-CAREER-001',
    title: '官印相生',
    appliesTo: ['career'],
    direction: 'positive',
    weight: 12,
    volatility: 5,
    confidence: 80,
    evidenceTag: '官印相生',
    explanation: '官印相生主事业稳定上升，贵人相助',
  },
  {
    sourceId: 'ZP-CAREER-002',
    title: '食伤制杀',
    appliesTo: ['career'],
    direction: 'positive',
    weight: 10,
    volatility: 10,
    confidence: 75,
    evidenceTag: '食伤制杀',
    explanation: '以才制杀，适合技术创业和突破瓶颈',
  },
  {
    sourceId: 'ZP-CAREER-003',
    title: '文昌助业',
    appliesTo: ['career', 'overall'],
    direction: 'positive',
    weight: 6,
    volatility: 3,
    confidence: 70,
    evidenceTag: '文昌贵人',
    explanation: '文昌贵人主学习和资质提升，利考试考证',
  },
  {
    sourceId: 'ZP-REL-001',
    title: '桃花触发',
    appliesTo: ['relationship'],
    direction: 'mixed',
    weight: 5,
    volatility: 15,
    confidence: 65,
    evidenceTag: '桃花',
    explanation: '桃花出现时情感波动大，可能是良缘也可能是烂桃花',
  },
  {
    sourceId: 'ZP-REL-002',
    title: '夫妻宫冲动',
    appliesTo: ['relationship'],
    direction: 'mixed',
    weight: 8,
    volatility: 18,
    confidence: 70,
    evidenceTag: '夫妻宫冲动',
    explanation: '日支被冲动主感情变化，可能是分手也可能是新开始',
  },
  {
    sourceId: 'ZP-REL-003',
    title: '红鸾天喜',
    appliesTo: ['relationship'],
    direction: 'positive',
    weight: 10,
    volatility: 6,
    confidence: 75,
    evidenceTag: '红鸾天喜',
    explanation: '红鸾天喜主婚恋喜事，利于感情推进',
  },
  {
    sourceId: 'ZP-RISK-001',
    title: '空亡回撤',
    appliesTo: ['overall', 'wealth', 'career', 'relationship'],
    direction: 'negative',
    weight: -8,
    volatility: 10,
    confidence: 70,
    evidenceTag: '空亡',
    explanation: '空亡主虚花不实，机会看得到但落不下来',
  },
  {
    sourceId: 'ZP-RISK-002',
    title: '冲刑破位',
    appliesTo: ['overall', 'wealth', 'career', 'relationship'],
    direction: 'negative',
    weight: -12,
    volatility: 15,
    confidence: 75,
    evidenceTag: '冲刑破位',
    explanation: '冲刑集中出现时波动加大，容易生变',
  },
  {
    sourceId: 'ZP-OVERALL-001',
    title: '用神回归',
    appliesTo: ['overall'],
    direction: 'positive',
    weight: 15,
    volatility: 5,
    confidence: 85,
    evidenceTag: '用神回归',
    explanation: '用神在大运或流年中重新增强，是人生重要转机',
  },

  {
    sourceId: 'SHI-001',
    title: '正官透干',
    appliesTo: ['career'],
    direction: 'positive',
    weight: 10,
    volatility: 5,
    confidence: 80,
    evidenceTag: '正官',
    explanation: '正官透干主贵人提携，事业有章法可循',
  },
  {
    sourceId: 'SHI-002',
    title: '七杀攻身',
    appliesTo: ['career'],
    direction: 'mixed',
    weight: 12,
    volatility: 14,
    confidence: 75,
    evidenceTag: '七杀',
    explanation: '七杀攻身压力与机遇并存，能扛则大成',
  },
  {
    sourceId: 'SHI-003',
    title: '正财合身',
    appliesTo: ['wealth'],
    direction: 'positive',
    weight: 10,
    volatility: 4,
    confidence: 80,
    evidenceTag: '正财',
    explanation: '正财合身主稳妥之财，薪资和资产稳步增长',
  },
  {
    sourceId: 'SHI-004',
    title: '偏财透出',
    appliesTo: ['wealth'],
    direction: 'mixed',
    weight: 10,
    volatility: 14,
    confidence: 72,
    evidenceTag: '偏财',
    explanation: '偏财透出主意外之财和投资机会，但波动较大',
  },
  {
    sourceId: 'SHI-005',
    title: '食神吐秀',
    appliesTo: ['career', 'overall'],
    direction: 'positive',
    weight: 8,
    volatility: 4,
    confidence: 78,
    evidenceTag: '食神',
    explanation: '食神吐秀主才华显露，利于创作和表达',
  },
  {
    sourceId: 'SHI-006',
    title: '伤官见官',
    appliesTo: ['career'],
    direction: 'negative',
    weight: 10,
    volatility: 13,
    confidence: 76,
    evidenceTag: '伤官',
    explanation: '伤官见官有违体制之象，需防口舌是非',
  },
  {
    sourceId: 'SHI-007',
    title: '比劫林立',
    appliesTo: ['wealth'],
    direction: 'negative',
    weight: 8,
    volatility: 10,
    confidence: 72,
    evidenceTag: '比劫',
    explanation: '比劫林立竞争激烈，钱财来去匆匆',
  },
  {
    sourceId: 'SHI-008',
    title: '印星护身',
    appliesTo: ['overall'],
    direction: 'positive',
    weight: 8,
    volatility: 3,
    confidence: 78,
    evidenceTag: '印星',
    explanation: '印星护身主有靠山，学习进修运佳',
  },

  {
    sourceId: 'XC-001',
    title: '三合局成',
    appliesTo: ['overall', 'career'],
    direction: 'positive',
    weight: 12,
    volatility: 6,
    confidence: 82,
    evidenceTag: '三合局',
    explanation: '三合局成主大事可期，三方力量汇聚',
  },
  {
    sourceId: 'XC-002',
    title: '六合局成',
    appliesTo: ['overall', 'relationship'],
    direction: 'positive',
    weight: 8,
    volatility: 4,
    confidence: 79,
    evidenceTag: '六合',
    explanation: '六合局成主顺利合作，人际关系融洽',
  },
  {
    sourceId: 'XC-003',
    title: '天克地冲',
    appliesTo: ['overall'],
    direction: 'negative',
    weight: 12,
    volatility: 16,
    confidence: 78,
    evidenceTag: '天克地冲',
    explanation: '天克地冲主剧烈变动，环境突然改变',
  },
  {
    sourceId: 'XC-004',
    title: '刑害并见',
    appliesTo: ['overall', 'relationship'],
    direction: 'negative',
    weight: 8,
    volatility: 10,
    confidence: 74,
    evidenceTag: '刑害',
    explanation: '刑害并见主暗中有阻，小人是非不断',
  },
  {
    sourceId: 'XC-005',
    title: '三刑全',
    appliesTo: ['relationship'],
    direction: 'negative',
    weight: 15,
    volatility: 18,
    confidence: 76,
    evidenceTag: '三刑',
    explanation: '三刑全见主关系紧张，需特别注意人际和法律',
  },
  {
    sourceId: 'XC-006',
    title: '暗合',
    appliesTo: ['relationship'],
    direction: 'mixed',
    weight: 5,
    volatility: 10,
    confidence: 60,
    evidenceTag: '暗合',
    explanation: '暗合主隐藏的情感和合作，表面平静暗流涌动',
  },

  {
    sourceId: 'SS-001',
    title: '天乙贵人临',
    appliesTo: ['overall'],
    direction: 'positive',
    weight: 10,
    volatility: 3,
    confidence: 82,
    evidenceTag: '天乙贵人',
    explanation: '天乙贵人乃命中最吉之神，逢之大有助力',
  },
  {
    sourceId: 'SS-002',
    title: '文昌入命',
    appliesTo: ['career'],
    direction: 'positive',
    weight: 8,
    volatility: 3,
    confidence: 78,
    evidenceTag: '文昌',
    explanation: '文昌入命利学术研究，考试考证有助力',
  },
  {
    sourceId: 'SS-003',
    title: '驿马发动',
    appliesTo: ['career'],
    direction: 'mixed',
    weight: 6,
    volatility: 12,
    confidence: 70,
    evidenceTag: '驿马',
    explanation: '驿马发动主奔波变动，适合异地发展',
  },
  {
    sourceId: 'SS-004',
    title: '羊刃驾杀',
    appliesTo: ['career'],
    direction: 'mixed',
    weight: 10,
    volatility: 15,
    confidence: 74,
    evidenceTag: '羊刃',
    explanation: '羊刃驾杀有魄力敢闯，但容易过激冒进',
  },
  {
    sourceId: 'SS-005',
    title: '孤辰寡宿',
    appliesTo: ['relationship'],
    direction: 'negative',
    weight: 8,
    volatility: 5,
    confidence: 68,
    evidenceTag: '孤辰',
    explanation: '孤辰寡宿主情感孤独，晚婚或独身倾向',
  },
  {
    sourceId: 'SS-006',
    title: '劫煞亡神',
    appliesTo: ['overall', 'wealth'],
    direction: 'negative',
    weight: 10,
    volatility: 14,
    confidence: 72,
    evidenceTag: '劫煞',
    explanation: '劫煞亡神主意外破财和突发变故',
  },

  {
    sourceId: 'DY-001',
    title: '换运交接',
    appliesTo: ['overall'],
    direction: 'mixed',
    weight: 10,
    volatility: 18,
    confidence: 76,
    evidenceTag: '换运',
    explanation: '换运交接是新旧交替时期，波动最大也机遇最多',
  },
  {
    sourceId: 'DY-002',
    title: '用神大运',
    appliesTo: ['overall'],
    direction: 'positive',
    weight: 15,
    volatility: 5,
    confidence: 84,
    evidenceTag: '用神大运',
    explanation: '用神大运是人生顺境，万事顺遂',
  },
  {
    sourceId: 'DY-003',
    title: '忌神大运',
    appliesTo: ['overall'],
    direction: 'negative',
    weight: 12,
    volatility: 14,
    confidence: 76,
    evidenceTag: '忌神大运',
    explanation: '忌神大运需谨慎行事，宜韬光养晦',
  },
  {
    sourceId: 'DY-004',
    title: '墓库运',
    appliesTo: ['overall'],
    direction: 'negative',
    weight: 8,
    volatility: 8,
    confidence: 68,
    evidenceTag: '墓库',
    explanation: '墓库运主困顿停滞，进展缓慢但非全无机会',
  },

  {
    sourceId: 'ZW-001',
    title: '紫微在命',
    appliesTo: ['overall'],
    direction: 'positive',
    weight: 12,
    volatility: 5,
    confidence: 80,
    evidenceTag: '紫微',
    explanation: '紫微在命有领袖气质，天生的管理者',
  },
  {
    sourceId: 'ZW-002',
    title: '杀破狼格',
    appliesTo: ['career'],
    direction: 'mixed',
    weight: 15,
    volatility: 20,
    confidence: 78,
    evidenceTag: '杀破狼',
    explanation: '杀破狼格局大起大落，不成大器即成大祸',
  },
  {
    sourceId: 'ZW-003',
    title: '禄在财帛',
    appliesTo: ['wealth'],
    direction: 'positive',
    weight: 12,
    volatility: 6,
    confidence: 80,
    evidenceTag: '禄在财帛',
    explanation: '禄在财帛主财源稳定，善于理财积累',
  },
  {
    sourceId: 'ZW-004',
    title: '忌在夫妻',
    appliesTo: ['relationship'],
    direction: 'negative',
    weight: 10,
    volatility: 12,
    confidence: 74,
    evidenceTag: '忌在夫妻',
    explanation: '忌在夫妻宫主感情不顺，婚姻需要更多经营',
  },
  {
    sourceId: 'ZW-005',
    title: '府相朝垣',
    appliesTo: ['overall'],
    direction: 'positive',
    weight: 10,
    volatility: 4,
    confidence: 78,
    evidenceTag: '府相',
    explanation: '府相朝垣有贵人守护，生活安稳有福',
  },
  {
    sourceId: 'ZW-006',
    title: '火铃夹命',
    appliesTo: ['overall'],
    direction: 'negative',
    weight: 12,
    volatility: 14,
    confidence: 74,
    evidenceTag: '火铃',
    explanation: '火铃夹命主压力重重，突发状况频繁',
  },
];

export function getFactorsByAspect(aspect: KlineAspect): KlineRuleFactor[] {
  return KLINE_RULE_FACTORS.filter((f) => f.appliesTo.includes(aspect));
}

export function getFactorWeight(evidenceTags: string[] | undefined, aspect: KlineAspect): number {
  if (!evidenceTags || evidenceTags.length === 0) return 0;
  const factors = getFactorsByAspect(aspect);
  let total = 0;
  for (const tag of evidenceTags) {
    const matched = factors.filter((f) => f.evidenceTag === tag || tag.includes(f.evidenceTag));
    for (const f of matched) {
      total += f.weight;
    }
  }
  return total;
}