import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const cases = [
  {
    source: '六壬断案详解',
    question: '某人占婚姻成否',
    askTime: '甲子日辰时',
    eventType: '婚姻',
    lessonData: JSON.stringify({
      yearGanZhi: '甲子', monthGanZhi: '丙寅', dayGanZhi: '甲子',
      tianPan: [{ shen: '贵人', zhi: '丑' }],
      siKe: [{ ri: '甲', shang: '子' }],
      sanChuan: [{ chu: '子', zhong: '寅', mo: '辰' }],
    }),
    judgment: '干支上神六合，天后临支，三传见青龙，婚姻可成。应期在三合填实之月。',
    verification: '三个月后成婚',
    keyPoints: JSON.stringify(['干支上神六合', '天后临支', '青龙入传']),
    keTi: '元首',
    tags: JSON.stringify(['婚姻', '成婚', '六合']),
    shenshaList: JSON.stringify(['天后', '青龙', '六合']),
    biFaList: JSON.stringify(['干支相会', '天后临日', '青龙入传']),
  },
  {
    source: '六壬断案详解',
    question: '某人占求财可否',
    askTime: '乙丑日巳时',
    eventType: '求财',
    lessonData: JSON.stringify({
      yearGanZhi: '乙丑', monthGanZhi: '丁卯', dayGanZhi: '乙丑',
      sanChuan: [{ chu: '寅', zhong: '辰', mo: '午' }],
    }),
    judgment: '青龙临日干，财星入传，三传递生，求财必得。宜往东方求之。',
    verification: '往东方贸易，获利颇丰',
    keyPoints: JSON.stringify(['青龙临干', '财星入传', '三传递生']),
    keTi: '三合',
    tags: JSON.stringify(['求财', '得财', '东方']),
    shenshaList: JSON.stringify(['青龙', '太常']),
    biFaList: JSON.stringify(['青龙入传', '三传递生']),
  },
  {
    source: '六壬断案详解',
    question: '某人占官讼胜负',
    askTime: '丙寅日午时',
    eventType: '官非',
    lessonData: JSON.stringify({
      yearGanZhi: '丙寅', monthGanZhi: '戊辰', dayGanZhi: '丙寅',
      sanChuan: [{ chu: '巳', zhong: '未', mo: '酉' }],
    }),
    judgment: '贵人临日干，勾陈生日干，干上神克勾陈，讼必得胜。然白虎入传，需防刑伤。',
    verification: '官司得胜，但耗费颇多',
    keyPoints: JSON.stringify(['贵人临干', '干克勾陈', '白虎入传']),
    keTi: '涉害',
    tags: JSON.stringify(['官非', '诉讼', '胜诉']),
    shenshaList: JSON.stringify(['贵人', '勾陈', '白虎']),
    biFaList: JSON.stringify(['贵人临身', '白虎入传']),
  },
  {
    source: '六壬断案详解',
    question: '某人占出行吉凶',
    askTime: '丁卯日申时',
    eventType: '出行',
    lessonData: JSON.stringify({
      yearGanZhi: '丁卯', monthGanZhi: '己巳', dayGanZhi: '丁卯',
      sanChuan: [{ chu: '午', zhong: '申', mo: '戌' }],
    }),
    judgment: '驿马发动临日干，青龙入传，轩盖课成，出行大吉。宜往西南。',
    verification: '出行顺利，途中遇贵人',
    keyPoints: JSON.stringify(['驿马发动', '青龙入传', '轩盖课']),
    keTi: '轩盖',
    tags: JSON.stringify(['出行', '顺利', '西南']),
    shenshaList: JSON.stringify(['驿马', '青龙']),
    biFaList: JSON.stringify(['驿马发动', '青龙入传']),
  },
  {
    source: '六壬断案详解',
    question: '某人占疾病吉凶',
    askTime: '戊辰日酉时',
    eventType: '疾病',
    lessonData: JSON.stringify({
      yearGanZhi: '戊辰', monthGanZhi: '庚午', dayGanZhi: '戊辰',
      sanChuan: [{ chu: '申', zhong: '戌', mo: '子' }],
    }),
    judgment: '白虎临日干，鬼临三四课，魄化课成，病势沉重。然青龙临末传，尚有一线生机。',
    verification: '病情危重，三月后方愈',
    keyPoints: JSON.stringify(['白虎临干', '鬼临三四', '魄化课', '青龙末传']),
    keTi: '魄化',
    tags: JSON.stringify(['疾病', '重症', '后愈']),
    shenshaList: JSON.stringify(['白虎', '青龙']),
    biFaList: JSON.stringify(['白虎入传', '鬼临三四']),
  },
  {
    source: '六壬断案详解',
    question: '某人占科举考试',
    askTime: '己巳日辰时',
    eventType: '考试',
    lessonData: JSON.stringify({
      yearGanZhi: '己巳', monthGanZhi: '辛未', dayGanZhi: '己巳',
      sanChuan: [{ chu: '未', zhong: '酉', mo: '亥' }],
    }),
    judgment: '贵人临日干，朱雀临干上神，铸印课成，考试必中。文笔出众，名列前茅。',
    verification: '科举中第，名列第三',
    keyPoints: JSON.stringify(['贵人临干', '朱雀临干', '铸印课']),
    keTi: '铸印',
    tags: JSON.stringify(['考试', '中第', '科举']),
    shenshaList: JSON.stringify(['贵人', '朱雀', '青龙']),
    biFaList: JSON.stringify(['贵人临身', '朱雀临门']),
  },
  {
    source: '六壬断案详解',
    question: '某人占失物可寻否',
    askTime: '庚午日戌时',
    eventType: '失物',
    lessonData: JSON.stringify({
      yearGanZhi: '庚午', monthGanZhi: '壬申', dayGanZhi: '庚午',
      sanChuan: [{ chu: '戌', zhong: '子', mo: '寅' }],
    }),
    judgment: '玄武临日干，主被盗。支上见财星，失物在西北方。初传生支上神，失物可回。',
    verification: '在西北方邻家寻回',
    keyPoints: JSON.stringify(['玄武临干', '支见财星', '初传生支']),
    keTi: '元首',
    tags: JSON.stringify(['失物', '可寻', '西北']),
    shenshaList: JSON.stringify(['玄武']),
    biFaList: JSON.stringify(['玄武入课']),
  },
  {
    source: '六壬断案详解',
    question: '某人占与人合伙',
    askTime: '辛未日子时',
    eventType: '合作',
    lessonData: JSON.stringify({
      yearGanZhi: '辛未', monthGanZhi: '癸酉', dayGanZhi: '辛未',
      sanChuan: [{ chu: '亥', zhong: '丑', mo: '卯' }],
    }),
    judgment: '干支上神相生，六合临三传，三合课成，合作大利。对方诚信可靠。',
    verification: '合作三年，获利丰厚',
    keyPoints: JSON.stringify(['干支相生', '六合临传', '三合课']),
    keTi: '三合',
    tags: JSON.stringify(['合作', '顺利', '获利']),
    shenshaList: JSON.stringify(['六合', '青龙']),
    biFaList: JSON.stringify(['干支相会', '青龙入传']),
  },
  {
    source: '六壬断案详解',
    question: '某人占购置田宅',
    askTime: '壬申日寅时',
    eventType: '田宅',
    lessonData: JSON.stringify({
      yearGanZhi: '壬申', monthGanZhi: '甲戌', dayGanZhi: '壬申',
      sanChuan: [{ chu: '辰', zhong: '戌', mo: '丑' }],
    }),
    judgment: '太常临支上神，稼穑课成，青龙临三传，置业大利。宜购东南方位。',
    verification: '购入宅院，后增值三倍',
    keyPoints: JSON.stringify(['太常临支', '稼穑课', '青龙入传']),
    keTi: '稼穑',
    tags: JSON.stringify(['田宅', '置业', '增值']),
    shenshaList: JSON.stringify(['太常', '青龙', '勾陈']),
    biFaList: JSON.stringify(['太常喜庆', '青龙入传']),
  },
  {
    source: '六壬断案详解',
    question: '某人占近日天气',
    askTime: '癸酉日卯时',
    eventType: '天时',
    lessonData: JSON.stringify({
      yearGanZhi: '癸酉', monthGanZhi: '乙亥', dayGanZhi: '癸酉',
      sanChuan: [{ chu: '子', zhong: '寅', mo: '辰' }],
    }),
    judgment: '青龙临三传，天后亦临传，近日有雨。三日后转晴，朱雀出。',
    verification: '次日大雨，三日后晴',
    keyPoints: JSON.stringify(['青龙临传', '天后临传']),
    keTi: '元首',
    tags: JSON.stringify(['天时', '有雨', '后晴']),
    shenshaList: JSON.stringify(['青龙', '天后', '朱雀']),
    biFaList: JSON.stringify([]),
  },
  {
    source: '林锋六壬实战进阶精通上',
    question: '某女士占与男友能否结婚',
    askTime: '甲戌日午时',
    eventType: '婚姻',
    lessonData: JSON.stringify({
      yearGanZhi: '甲戌', monthGanZhi: '丙子', dayGanZhi: '甲戌',
      sanChuan: [{ chu: '丑', zhong: '亥', mo: '酉' }],
    }),
    judgment: '支上神生干上神，女方主动。天后临支，六合入传，婚事可成。但别责课成，男方犹豫。',
    verification: '女方主动求婚，半年后成婚',
    keyPoints: JSON.stringify(['支生干', '天后临支', '六合入传', '别责课']),
    keTi: '别责',
    tags: JSON.stringify(['婚姻', '女追男', '成婚']),
    shenshaList: JSON.stringify(['天后', '六合']),
    biFaList: JSON.stringify(['天后临日']),
  },
  {
    source: '林锋六壬实战进阶精通上',
    question: '某商人占今年财运',
    askTime: '乙亥日巳时',
    eventType: '求财',
    lessonData: JSON.stringify({
      yearGanZhi: '乙亥', monthGanZhi: '丁丑', dayGanZhi: '乙亥',
      sanChuan: [{ chu: '寅', zhong: '午', mo: '戌' }],
    }),
    judgment: '青龙临三传，财星入初传，德禄临身，今年财运亨通。然末传见空亡，年底需谨慎。',
    verification: '上半年获利百万，年底亏损三成',
    keyPoints: JSON.stringify(['青龙入传', '财星初传', '德禄临身', '末传空亡']),
    keTi: '三合',
    tags: JSON.stringify(['求财', '财运', '先得后失']),
    shenshaList: JSON.stringify(['青龙', '天空']),
    biFaList: JSON.stringify(['青龙入传', '德禄临身', '三传空亡']),
  },
  {
    source: '林锋六壬实战进阶精通上',
    question: '某人占公司内部纠纷',
    askTime: '丙子日申时',
    eventType: '官非',
    lessonData: JSON.stringify({
      yearGanZhi: '丙子', monthGanZhi: '戊寅', dayGanZhi: '丙子',
      sanChuan: [{ chu: '午', zhong: '辰', mo: '寅' }],
    }),
    judgment: '朱雀临门，勾陈临日，三刑课成，口舌官非难免。然贵人临末传，终有解救。',
    verification: '被举报调查，三月后贵人相助化解',
    keyPoints: JSON.stringify(['朱雀临门', '勾陈临日', '三刑课', '贵人末传']),
    keTi: '三刑',
    tags: JSON.stringify(['官非', '纠纷', '化解']),
    shenshaList: JSON.stringify(['朱雀', '勾陈', '贵人']),
    biFaList: JSON.stringify(['朱雀临门', '勾陈临日', '贵人临身']),
  },
  {
    source: '林锋六壬实战进阶精通上',
    question: '某人占出国留学可否',
    askTime: '丁丑日寅时',
    eventType: '出行',
    lessonData: JSON.stringify({
      yearGanZhi: '丁丑', monthGanZhi: '己卯', dayGanZhi: '丁丑',
      sanChuan: [{ chu: '申', zhong: '戌', mo: '子' }],
    }),
    judgment: '斩关课成，驿马发动，出国可成。但魁度天门，签证有阻，需耐心等待。',
    verification: '签证被拒一次，三个月后获批',
    keyPoints: JSON.stringify(['斩关课', '驿马发动', '魁度天门']),
    keTi: '斩关',
    tags: JSON.stringify(['出行', '出国', '签证']),
    shenshaList: JSON.stringify(['驿马', '青龙']),
    biFaList: JSON.stringify(['驿马发动', '魁度天门']),
  },
  {
    source: '林锋六壬实战进阶精通上',
    question: '某人占母亲病况',
    askTime: '戊寅日酉时',
    eventType: '疾病',
    lessonData: JSON.stringify({
      yearGanZhi: '戊寅', monthGanZhi: '庚辰', dayGanZhi: '戊寅',
      sanChuan: [{ chu: '子', zhong: '戌', mo: '申' }],
    }),
    judgment: '白虎临支上神（支为母），鬼临三四，病势不轻。然生气临初传，尚可救治。宜往南就医。',
    verification: '往南方医院治疗，两月后康复',
    keyPoints: JSON.stringify(['白虎临支', '鬼临三四', '生气初传']),
    keTi: '涉害',
    tags: JSON.stringify(['疾病', '母病', '可治']),
    shenshaList: JSON.stringify(['白虎']),
    biFaList: JSON.stringify(['鬼临三四']),
  },
  {
    source: '林锋六壬实战进阶精通中',
    question: '某学生占高考能否上线',
    askTime: '己卯日辰时',
    eventType: '考试',
    lessonData: JSON.stringify({
      yearGanZhi: '己卯', monthGanZhi: '辛巳', dayGanZhi: '己卯',
      sanChuan: [{ chu: '酉', zhong: '未', mo: '巳' }],
    }),
    judgment: '朱雀临干上神，文笔尚可。但涉害课成，竞争激烈。德禄临身，终有希望。',
    verification: '勉强过线，被二本院校录取',
    keyPoints: JSON.stringify(['朱雀临干', '涉害课', '德禄临身']),
    keTi: '涉害',
    tags: JSON.stringify(['考试', '高考', '过线']),
    shenshaList: JSON.stringify(['朱雀', '贵人']),
    biFaList: JSON.stringify(['朱雀临门', '德禄临身']),
  },
  {
    source: '林锋六壬实战进阶精通中',
    question: '某公司占丢失重要文件',
    askTime: '庚辰日亥时',
    eventType: '失物',
    lessonData: JSON.stringify({
      yearGanZhi: '庚辰', monthGanZhi: '壬午', dayGanZhi: '庚辰',
      sanChuan: [{ chu: '子', zhong: '寅', mo: '辰' }],
    }),
    judgment: '玄武临日干，疑为内部人所为。支上见贵人，有贵人相助寻回。闭口课成，暂勿声张。',
    verification: '内部调查后，三日内寻回',
    keyPoints: JSON.stringify(['玄武临干', '贵人临支', '闭口课']),
    keTi: '闭口',
    tags: JSON.stringify(['失物', '内部', '寻回']),
    shenshaList: JSON.stringify(['玄武', '贵人']),
    biFaList: JSON.stringify(['玄武入课', '贵人临身']),
  },
  {
    source: '林锋六壬实战进阶精通中',
    question: '两人占合伙开店可否',
    askTime: '辛巳日午时',
    eventType: '合作',
    lessonData: JSON.stringify({
      yearGanZhi: '辛巳', monthGanZhi: '癸未', dayGanZhi: '辛巳',
      sanChuan: [{ chu: '未', zhong: '巳', mo: '卯' }],
    }),
    judgment: '干支上神相克，合作恐不和。玄武临支上神，对方有隐情。建议暂缓。',
    verification: '未合作，后知对方负债百万',
    keyPoints: JSON.stringify(['干支相克', '玄武临支', '建议暂缓']),
    keTi: '重审',
    tags: JSON.stringify(['合作', '不宜', '对方有诈']),
    shenshaList: JSON.stringify(['玄武', '天空']),
    biFaList: JSON.stringify(['干支相克', '玄武入课']),
  },
  {
    source: '林锋六壬实战进阶精通中',
    question: '某人占祖宅风水',
    askTime: '壬午日巳时',
    eventType: '田宅',
    lessonData: JSON.stringify({
      yearGanZhi: '壬午', monthGanZhi: '甲申', dayGanZhi: '壬午',
      sanChuan: [{ chu: '丑', zhong: '亥', mo: '酉' }],
    }),
    judgment: '勾陈临支上神克干，祖宅有纠纷隐患。天空临支，宅气空虚。建议修缮后入住。',
    verification: '修缮祖宅后，家庭和睦',
    keyPoints: JSON.stringify(['勾陈克干', '天空临支']),
    keTi: '伏吟',
    tags: JSON.stringify(['田宅', '祖宅', '修缮']),
    shenshaList: JSON.stringify(['勾陈', '天空']),
    biFaList: JSON.stringify(['勾陈临日']),
  },
  {
    source: '林锋六壬实战进阶精通中',
    question: '某农户占明日天气',
    askTime: '癸未日卯时',
    eventType: '天时',
    lessonData: JSON.stringify({
      yearGanZhi: '癸未', monthGanZhi: '乙酉', dayGanZhi: '癸未',
      sanChuan: [{ chu: '寅', zhong: '子', mo: '戌' }],
    }),
    judgment: '青龙临三传，天后亦现，明日有雨。朱雀不现，非晴天。宜备雨具。',
    verification: '次日阴雨',
    keyPoints: JSON.stringify(['青龙临传', '天后临传']),
    keTi: '元首',
    tags: JSON.stringify(['天时', '有雨']),
    shenshaList: JSON.stringify(['青龙', '天后']),
    biFaList: JSON.stringify([]),
  },
  {
    source: '六壬指南例题解',
    question: '占某官员能否升迁',
    askTime: '甲申日辰时',
    eventType: '考试',
    lessonData: JSON.stringify({
      yearGanZhi: '甲申', monthGanZhi: '丙戌', dayGanZhi: '甲申',
      sanChuan: [{ chu: '巳', zhong: '卯', mo: '丑' }],
    }),
    judgment: '铸印课成，贵人临身，青龙入传，升迁在即。然涉害课兼见，竞争激烈，需防小人。',
    verification: '三月后升迁，但遭同僚弹劾',
    keyPoints: JSON.stringify(['铸印课', '贵人临身', '青龙入传', '涉害兼见']),
    keTi: '铸印',
    tags: JSON.stringify(['升迁', '官运', '竞争']),
    shenshaList: JSON.stringify(['贵人', '青龙']),
    biFaList: JSON.stringify(['贵人临身', '青龙入传']),
  },
  {
    source: '六壬指南例题解',
    question: '占某商人出海贸易',
    askTime: '乙酉日午时',
    eventType: '求财',
    lessonData: JSON.stringify({
      yearGanZhi: '乙酉', monthGanZhi: '丁亥', dayGanZhi: '乙酉',
      sanChuan: [{ chu: '午', zhong: '辰', mo: '寅' }],
    }),
    judgment: '轩盖课成，驿马青龙俱现，远行求财大利。宜往东南海上。',
    verification: '出海贸易，获利十倍',
    keyPoints: JSON.stringify(['轩盖课', '驿马', '青龙']),
    keTi: '轩盖',
    tags: JSON.stringify(['求财', '出海', '大利']),
    shenshaList: JSON.stringify(['驿马', '青龙']),
    biFaList: JSON.stringify(['驿马发动', '青龙入传']),
  },
  {
    source: '六壬指南例题解',
    question: '占某人被捕后能否获释',
    askTime: '丙戌日酉时',
    eventType: '官非',
    lessonData: JSON.stringify({
      yearGanZhi: '丙戌', monthGanZhi: '戊子', dayGanZhi: '丙戌',
      sanChuan: [{ chu: '亥', zhong: '酉', mo: '未' }],
    }),
    judgment: '天狱课成，勾陈白虎俱临，牢狱之灾难免。然贵人临末传，终有出狱之日。',
    verification: '入狱三年后获释',
    keyPoints: JSON.stringify(['天狱课', '勾陈', '白虎', '贵人末传']),
    keTi: '天狱',
    tags: JSON.stringify(['官非', '牢狱', '获释']),
    shenshaList: JSON.stringify(['勾陈', '白虎', '贵人']),
    biFaList: JSON.stringify(['勾陈临日', '白虎入传', '贵人临身']),
  },
  {
    source: '六壬指南例题解',
    question: '占某将军出征吉凶',
    askTime: '丁亥日寅时',
    eventType: '出行',
    lessonData: JSON.stringify({
      yearGanZhi: '丁亥', monthGanZhi: '己丑', dayGanZhi: '丁亥',
      sanChuan: [{ chu: '申', zhong: '午', mo: '辰' }],
    }),
    judgment: '斩关课成，龙战兼见，出征可胜但必有血战。驿马青龙助力，速战速决。',
    verification: '出征大胜，但伤亡过半',
    keyPoints: JSON.stringify(['斩关课', '龙战', '驿马', '青龙']),
    keTi: '斩关',
    tags: JSON.stringify(['出行', '出征', '血战']),
    shenshaList: JSON.stringify(['驿马', '青龙', '白虎']),
    biFaList: JSON.stringify(['驿马发动', '青龙入传', '白虎入传']),
  },
  {
    source: '六壬指南例题解',
    question: '占某妇人难产吉凶',
    askTime: '戊子日巳时',
    eventType: '疾病',
    lessonData: JSON.stringify({
      yearGanZhi: '戊子', monthGanZhi: '庚寅', dayGanZhi: '戊子',
      sanChuan: [{ chu: '子', zhong: '戌', mo: '申' }],
    }),
    judgment: '白虎临支，魄化课成，生产大凶。然青龙临末传，母子或有一线生机。速请名医。',
    verification: '难产三日，母子最终平安',
    keyPoints: JSON.stringify(['白虎临支', '魄化课', '青龙末传']),
    keTi: '魄化',
    tags: JSON.stringify(['疾病', '难产', '平安']),
    shenshaList: JSON.stringify(['白虎', '青龙']),
    biFaList: JSON.stringify(['白虎入传']),
  },
  {
    source: '六壬指南例题解',
    question: '占某考生乡试能否中举',
    askTime: '己丑日卯时',
    eventType: '考试',
    lessonData: JSON.stringify({
      yearGanZhi: '己丑', monthGanZhi: '辛卯', dayGanZhi: '己丑',
      sanChuan: [{ chu: '酉', zhong: '亥', mo: '丑' }],
    }),
    judgment: '元首课成，朱雀贵人俱临，文笔出众，必中无疑。名次在前三。',
    verification: '乡试中第二名',
    keyPoints: JSON.stringify(['元首课', '朱雀', '贵人']),
    keTi: '元首',
    tags: JSON.stringify(['考试', '中举', '乡试']),
    shenshaList: JSON.stringify(['朱雀', '贵人']),
    biFaList: JSON.stringify(['朱雀临门', '贵人临身']),
  },
  {
    source: '六壬指南例题解',
    question: '占某人家中被盗失物',
    askTime: '庚寅日戌时',
    eventType: '失物',
    lessonData: JSON.stringify({
      yearGanZhi: '庚寅', monthGanZhi: '壬辰', dayGanZhi: '庚寅',
      sanChuan: [{ chu: '子', zhong: '戌', mo: '申' }],
    }),
    judgment: '玄武临日干，确为盗贼。支上见财星在北方，初传克玄武，盗贼可擒。速报官。',
    verification: '报官后三日内擒贼，失物追回大半',
    keyPoints: JSON.stringify(['玄武临干', '财星在支', '初传克玄武']),
    keTi: '重审',
    tags: JSON.stringify(['失物', '被盗', '追回']),
    shenshaList: JSON.stringify(['玄武', '勾陈']),
    biFaList: JSON.stringify(['玄武入课']),
  },
  {
    source: '六壬指南例题解',
    question: '两人占合伙经营盐业',
    askTime: '辛卯日午时',
    eventType: '合作',
    lessonData: JSON.stringify({
      yearGanZhi: '辛卯', monthGanZhi: '癸巳', dayGanZhi: '辛卯',
      sanChuan: [{ chu: '亥', zhong: '丑', mo: '卯' }],
    }),
    judgment: '干支上神六合，三合课成，六合临传，合作大利。盐业属水，正合局气。',
    verification: '合伙三年，获利丰厚，成一方巨贾',
    keyPoints: JSON.stringify(['干支六合', '三合课', '六合临传']),
    keTi: '三合',
    tags: JSON.stringify(['合作', '盐业', '大利']),
    shenshaList: JSON.stringify(['六合', '青龙', '太常']),
    biFaList: JSON.stringify(['干支相会', '青龙入传']),
  },
  {
    source: '六壬指南例题解',
    question: '占某富商购置庄园',
    askTime: '壬辰日巳时',
    eventType: '田宅',
    lessonData: JSON.stringify({
      yearGanZhi: '壬辰', monthGanZhi: '甲午', dayGanZhi: '壬辰',
      sanChuan: [{ chu: '丑', zhong: '卯', mo: '巳' }],
    }),
    judgment: '稼穑课成，太常临支，青龙入传，置业上吉。但勾陈临干，注意田契纠纷。',
    verification: '购入庄园，后因田契打了半年官司',
    keyPoints: JSON.stringify(['稼穑课', '太常临支', '青龙入传', '勾陈临干']),
    keTi: '稼穑',
    tags: JSON.stringify(['田宅', '庄园', '纠纷']),
    shenshaList: JSON.stringify(['太常', '青龙', '勾陈']),
    biFaList: JSON.stringify(['太常喜庆', '青龙入传', '勾陈临日']),
  },
  {
    source: '六壬指南例题解',
    question: '占某日是否宜嫁娶',
    askTime: '癸巳日辰时',
    eventType: '婚姻',
    lessonData: JSON.stringify({
      yearGanZhi: '癸巳', monthGanZhi: '乙未', dayGanZhi: '癸巳',
      sanChuan: [{ chu: '卯', zhong: '丑', mo: '亥' }],
    }),
    judgment: '天后临日，六合临三传，太常喜庆临支，嫁娶大吉。三合课成，百年好合。',
    verification: '当日成婚，夫妻和美',
    keyPoints: JSON.stringify(['天后临日', '六合临传', '太常临支', '三合课']),
    keTi: '三合',
    tags: JSON.stringify(['婚姻', '嫁娶', '大吉']),
    shenshaList: JSON.stringify(['天后', '六合', '太常']),
    biFaList: JSON.stringify(['天后临日', '太常喜庆']),
  },
  {
    source: '林锋六壬实战进阶精通下',
    question: '某女占丈夫外遇是否属实',
    askTime: '甲午日申时',
    eventType: '婚姻',
    lessonData: JSON.stringify({
      yearGanZhi: '甲午', monthGanZhi: '丙申', dayGanZhi: '甲午',
      sanChuan: [{ chu: '午', zhong: '辰', mo: '寅' }],
    }),
    judgment: '支上见玄武乘天后，确有隐情。螣蛇缠绕临干，女方心神不宁。八专课成，第三者插足。',
    verification: '确有其事，半年后离婚',
    keyPoints: JSON.stringify(['玄武乘天后', '螣蛇缠绕', '八专课']),
    keTi: '八专',
    tags: JSON.stringify(['婚姻', '外遇', '离婚']),
    shenshaList: JSON.stringify(['玄武', '天后', '螣蛇']),
    biFaList: JSON.stringify(['玄武入课', '螣蛇缠绕', '天后临日']),
  },
  {
    source: '林锋六壬实战进阶精通下',
    question: '某老板占投资新项目可否',
    askTime: '乙未日巳时',
    eventType: '求财',
    lessonData: JSON.stringify({
      yearGanZhi: '乙未', monthGanZhi: '丁酉', dayGanZhi: '乙未',
      sanChuan: [{ chu: '申', zhong: '午', mo: '辰' }],
    }),
    judgment: '天空临日干，玄武临财星，此项目虚多实少，恐为骗局。无禄课成，投资必亏。',
    verification: '未投资，后知该项目确为骗局',
    keyPoints: JSON.stringify(['天空临干', '玄武临财', '无禄课']),
    keTi: '无禄',
    tags: JSON.stringify(['求财', '骗局', '不宜']),
    shenshaList: JSON.stringify(['天空', '玄武']),
    biFaList: JSON.stringify(['天空无成', '玄武入课']),
  },
  {
    source: '林锋六壬实战进阶精通下',
    question: '某人占被辞退后能否维权',
    askTime: '丙申日酉时',
    eventType: '官非',
    lessonData: JSON.stringify({
      yearGanZhi: '丙申', monthGanZhi: '戊戌', dayGanZhi: '丙申',
      sanChuan: [{ chu: '亥', zhong: '丑', mo: '卯' }],
    }),
    judgment: '贵人临日干，勾陈生日干，维权有利。朱雀临干，文书证据充分。仲裁可胜。',
    verification: '劳动仲裁胜诉，获赔三个月工资',
    keyPoints: JSON.stringify(['贵人临干', '勾陈生干', '朱雀临干']),
    keTi: '知一',
    tags: JSON.stringify(['官非', '维权', '胜诉']),
    shenshaList: JSON.stringify(['贵人', '勾陈', '朱雀']),
    biFaList: JSON.stringify(['贵人临身', '朱雀临门']),
  },
  {
    source: '林锋六壬实战进阶精通下',
    question: '某人占去西藏旅游是否安全',
    askTime: '丁酉日寅时',
    eventType: '出行',
    lessonData: JSON.stringify({
      yearGanZhi: '丁酉', monthGanZhi: '己亥', dayGanZhi: '丁酉',
      sanChuan: [{ chu: '申', zhong: '午', mo: '辰' }],
    }),
    judgment: '驿马发动，游子课成，远行可去。但白虎临驿马，路途有险。建议推迟一月。',
    verification: '推迟一月后出行，一切顺利',
    keyPoints: JSON.stringify(['驿马发动', '游子课', '白虎临驿马']),
    keTi: '游子',
    tags: JSON.stringify(['出行', '西藏', '推迟']),
    shenshaList: JSON.stringify(['驿马', '白虎']),
    biFaList: JSON.stringify(['驿马发动', '白虎入传']),
  },
  {
    source: '林锋六壬实战进阶精通下',
    question: '某人占长期失眠原因',
    askTime: '戊戌日子时',
    eventType: '疾病',
    lessonData: JSON.stringify({
      yearGanZhi: '戊戌', monthGanZhi: '庚子', dayGanZhi: '戊戌',
      sanChuan: [{ chu: '辰', zhong: '寅', mo: '子' }],
    }),
    judgment: '罡塞鬼户课成，螣蛇缠绕临干，心神不宁。青龙不现，气血不足。宜中医调理。',
    verification: '中医调理三月，失眠好转',
    keyPoints: JSON.stringify(['罡塞鬼户', '螣蛇缠绕', '青龙不现']),
    keTi: '伏吟',
    tags: JSON.stringify(['疾病', '失眠', '中医']),
    shenshaList: JSON.stringify(['螣蛇']),
    biFaList: JSON.stringify(['罡塞鬼户', '螣蛇缠绕']),
  },
  {
    source: '林锋六壬实战进阶精通下',
    question: '某考生占考研能否上岸',
    askTime: '己亥日辰时',
    eventType: '考试',
    lessonData: JSON.stringify({
      yearGanZhi: '己亥', monthGanZhi: '辛丑', dayGanZhi: '己亥',
      sanChuan: [{ chu: '卯', zhong: '丑', mo: '亥' }],
    }),
    judgment: '朱雀临干，斫轮课成，考试有突破。但天空临末传，需防面试环节出问题。',
    verification: '笔试通过，面试被刷，调剂后上岸',
    keyPoints: JSON.stringify(['朱雀临干', '斫轮课', '天空末传']),
    keTi: '斫轮',
    tags: JSON.stringify(['考试', '考研', '调剂']),
    shenshaList: JSON.stringify(['朱雀', '天空']),
    biFaList: JSON.stringify(['朱雀临门']),
  },
  {
    source: '林锋六壬实战进阶精通下',
    question: '某女士占丢失金项链',
    askTime: '庚子日亥时',
    eventType: '失物',
    lessonData: JSON.stringify({
      yearGanZhi: '庚子', monthGanZhi: '壬寅', dayGanZhi: '庚子',
      sanChuan: [{ chu: '丑', zhong: '亥', mo: '酉' }],
    }),
    judgment: '玄武不临日干，非外人偷窃。支上见财星在西南卧室，自己放忘位置。回去找即可。',
    verification: '在卧室抽屉夹层中找到',
    keyPoints: JSON.stringify(['玄武不临干', '支见财星', '西南卧室']),
    keTi: '元首',
    tags: JSON.stringify(['失物', '遗忘', '卧室']),
    shenshaList: JSON.stringify([]),
    biFaList: JSON.stringify([]),
  },
  {
    source: '林锋六壬实战进阶精通下',
    question: '三人占合伙开餐厅',
    askTime: '辛丑日午时',
    eventType: '合作',
    lessonData: JSON.stringify({
      yearGanZhi: '辛丑', monthGanZhi: '癸卯', dayGanZhi: '辛丑',
      sanChuan: [{ chu: '卯', zhong: '巳', mo: '未' }],
    }),
    judgment: '干支上神相生，六合临传，太常喜庆临支，餐饮业大利。三合课成，三人同心。',
    verification: '开业后生意火爆，半年回本',
    keyPoints: JSON.stringify(['干支相生', '六合临传', '太常临支', '三合课']),
    keTi: '三合',
    tags: JSON.stringify(['合作', '餐饮', '火爆']),
    shenshaList: JSON.stringify(['六合', '太常', '青龙']),
    biFaList: JSON.stringify(['干支相会', '太常喜庆', '青龙入传']),
  },
  {
    source: '林锋六壬实战进阶精通下',
    question: '某人占购买二手房风水',
    askTime: '壬寅日巳时',
    eventType: '田宅',
    lessonData: JSON.stringify({
      yearGanZhi: '壬寅', monthGanZhi: '甲辰', dayGanZhi: '壬寅',
      sanChuan: [{ chu: '未', zhong: '巳', mo: '卯' }],
    }),
    judgment: '太常临支上神，宅舍尚可。但白虎临支下神，宅有旧伤。天空临三传，需防虚报面积。',
    verification: '购买后发现实际面积少5平，交涉后退差价',
    keyPoints: JSON.stringify(['太常临支', '白虎临支下', '天空临传']),
    keTi: '重审',
    tags: JSON.stringify(['田宅', '二手房', '面积不符']),
    shenshaList: JSON.stringify(['太常', '白虎', '天空']),
    biFaList: JSON.stringify(['白虎入传', '天空无成']),
  },
  {
    source: '六壬神课金口诀现代实例精解',
    question: '某人占当日面试结果（金口诀）',
    askTime: '癸卯日巳时',
    eventType: '考试',
    lessonData: JSON.stringify({
      method: 'jin_kou_jue',
      diFen: '卯', yueJiang: '青龙寅', guiShen: '贵人丑', renYuan: '乙',
      keTi: '神生将',
    }),
    judgment: '神生将，贵人相助之象。青龙临将，面试官赏识。人元乙木生地分卯木，根基稳固。面试必过。',
    verification: '面试通过，次日收到offer',
    keyPoints: JSON.stringify(['神生将', '青龙临将', '人元生地分']),
    keTi: '神生将',
    tags: JSON.stringify(['面试', '金口诀', '通过']),
    shenshaList: JSON.stringify(['贵人', '青龙']),
    biFaList: JSON.stringify([]),
  },
  {
    source: '六壬神课金口诀现代实例精解',
    question: '某人占合作谈判（金口诀）',
    askTime: '甲辰日午时',
    eventType: '合作',
    lessonData: JSON.stringify({
      method: 'jin_kou_jue',
      diFen: '午', yueJiang: '六合卯', guiShen: '螣蛇巳', renYuan: '丙',
      keTi: '神克将',
    }),
    judgment: '神克将，贵人不助。螣蛇临神，对方有诈。干克神，可主动压制。谈判需强势，否则吃亏。',
    verification: '强势谈判，对方让步，签约成功',
    keyPoints: JSON.stringify(['神克将', '螣蛇临神', '干克神']),
    keTi: '神克将',
    tags: JSON.stringify(['合作', '谈判', '强势']),
    shenshaList: JSON.stringify(['螣蛇', '六合']),
    biFaList: JSON.stringify([]),
  },
  {
    source: '六壬神课金口诀现代实例精解',
    question: '某人占近期财运（金口诀）',
    askTime: '乙巳日申时',
    eventType: '求财',
    lessonData: JSON.stringify({
      method: 'jin_kou_jue',
      diFen: '申', yueJiang: '青龙寅', guiShen: '太常未', renYuan: '庚',
      keTi: '将生干',
    }),
    judgment: '将生干，财来找人之象。青龙太常俱临，大财入库。四位纯阳，财运明朗。本月必有大财。',
    verification: '月中中奖十万',
    keyPoints: JSON.stringify(['将生干', '青龙临将', '太常临神', '四位纯阳']),
    keTi: '四位纯阳',
    tags: JSON.stringify(['求财', '中奖', '大财']),
    shenshaList: JSON.stringify(['青龙', '太常']),
    biFaList: JSON.stringify([]),
  },
  {
    source: '六壬神课金口诀现代实例精解',
    question: '某人占婚恋（金口诀）',
    askTime: '丙午日卯时',
    eventType: '婚姻',
    lessonData: JSON.stringify({
      method: 'jin_kou_jue',
      diFen: '卯', yueJiang: '天后子', guiShen: '六合卯', renYuan: '乙',
      keTi: '神将同宫',
    }),
    judgment: '神将同宫，事归一也。天后六合同宫临卯，桃花正旺。方生将，对方主动。婚事必成。',
    verification: '三月后结婚',
    keyPoints: JSON.stringify(['神将同宫', '天后六合同宫', '方生将']),
    keTi: '神将同宫',
    tags: JSON.stringify(['婚姻', '桃花', '成婚']),
    shenshaList: JSON.stringify(['天后', '六合']),
    biFaList: JSON.stringify([]),
  },
  {
    source: '六壬神课金口诀现代实例精解',
    question: '某人占官司胜负（金口诀）',
    askTime: '丁未日酉时',
    eventType: '官非',
    lessonData: JSON.stringify({
      method: 'jin_kou_jue',
      diFen: '酉', yueJiang: '白虎申', guiShen: '勾陈辰', renYuan: '辛',
      keTi: '干克神',
    }),
    judgment: '干克神，主动出击可胜。白虎勾陈俱现，官司难免但可胜。将克方，根基不稳但主动有利。',
    verification: '主动起诉，一审胜诉',
    keyPoints: JSON.stringify(['干克神', '白虎临将', '勾陈临神']),
    keTi: '干克神',
    tags: JSON.stringify(['官非', '胜诉', '主动']),
    shenshaList: JSON.stringify(['白虎', '勾陈']),
    biFaList: JSON.stringify([]),
  },
  {
    source: '大六壬高级预测学',
    question: '某企业家占公司上市前景',
    askTime: '戊申日辰时',
    eventType: '求财',
    lessonData: JSON.stringify({
      yearGanZhi: '戊申', monthGanZhi: '庚戌', dayGanZhi: '戊申',
      sanChuan: [{ chu: '巳', zhong: '卯', mo: '丑' }],
    }),
    judgment: '铸印课成，贵人青龙俱临，上市可成。但三传递克，过程坎坷。末传空亡，上市后股价需谨慎。',
    verification: '一年后上市，首日大涨后连跌三月',
    keyPoints: JSON.stringify(['铸印课', '贵人', '青龙', '三传递克', '末传空亡']),
    keTi: '铸印',
    tags: JSON.stringify(['求财', '上市', '先涨后跌']),
    shenshaList: JSON.stringify(['贵人', '青龙']),
    biFaList: JSON.stringify(['贵人临身', '青龙入传', '三传递克']),
  },
  {
    source: '大六壬高级预测学',
    question: '某官员占被调查后仕途',
    askTime: '己酉日申时',
    eventType: '官非',
    lessonData: JSON.stringify({
      yearGanZhi: '己酉', monthGanZhi: '辛亥', dayGanZhi: '己酉',
      sanChuan: [{ chu: '亥', zhong: '丑', mo: '卯' }],
    }),
    judgment: '天网课成，朱雀勾陈俱临，调查属实。白虎入传，恐有刑责。贵人不见，无人可救。',
    verification: '被查实后入狱五年',
    keyPoints: JSON.stringify(['天网课', '朱雀', '勾陈', '白虎入传', '贵人不现']),
    keTi: '天网',
    tags: JSON.stringify(['官非', '调查', '入狱']),
    shenshaList: JSON.stringify(['朱雀', '勾陈', '白虎']),
    biFaList: JSON.stringify(['朱雀临门', '勾陈临日', '白虎入传']),
  },
  {
    source: '大六壬高级预测学',
    question: '某留学生占毕业后去向',
    askTime: '庚戌日午时',
    eventType: '出行',
    lessonData: JSON.stringify({
      yearGanZhi: '庚戌', monthGanZhi: '壬子', dayGanZhi: '庚戌',
      sanChuan: [{ chu: '寅', zhong: '子', mo: '戌' }],
    }),
    judgment: '驿马临日干，游子课成，必动。魁度天门，不宜留国外。青龙在支，回国发展更佳。',
    verification: '毕业后回国，在央企就职',
    keyPoints: JSON.stringify(['驿马临干', '游子课', '魁度天门', '青龙在支']),
    keTi: '游子',
    tags: JSON.stringify(['出行', '回国', '央企']),
    shenshaList: JSON.stringify(['驿马', '青龙']),
    biFaList: JSON.stringify(['驿马发动', '魁度天门']),
  },
  {
    source: '大六壬高级预测学',
    question: '某人占父亲心脏病手术',
    askTime: '辛亥日巳时',
    eventType: '疾病',
    lessonData: JSON.stringify({
      yearGanZhi: '辛亥', monthGanZhi: '癸丑', dayGanZhi: '辛亥',
      sanChuan: [{ chu: '子', zhong: '戌', mo: '申' }],
    }),
    judgment: '白虎临支（支为父），魄化课成，手术风险极高。然青龙临末传，手术若过则愈。建议请名医主刀。',
    verification: '请名医手术，成功康复',
    keyPoints: JSON.stringify(['白虎临支', '魄化课', '青龙末传']),
    keTi: '魄化',
    tags: JSON.stringify(['疾病', '手术', '成功']),
    shenshaList: JSON.stringify(['白虎', '青龙']),
    biFaList: JSON.stringify(['白虎入传']),
  },
  {
    source: '大六壬高级预测学',
    question: '某律师占代理大案胜负',
    askTime: '壬子日辰时',
    eventType: '官非',
    lessonData: JSON.stringify({
      yearGanZhi: '壬子', monthGanZhi: '甲寅', dayGanZhi: '壬子',
      sanChuan: [{ chu: '卯', zhong: '丑', mo: '亥' }],
    }),
    judgment: '朱雀临干，文书有利。贵人临三传，法官公正。干上神克勾陈，必胜诉。斫轮课成，一战成名。',
    verification: '胜诉，律师因此案名声大噪',
    keyPoints: JSON.stringify(['朱雀临干', '贵人临传', '干克勾陈', '斫轮课']),
    keTi: '斫轮',
    tags: JSON.stringify(['官非', '胜诉', '成名']),
    shenshaList: JSON.stringify(['朱雀', '贵人', '勾陈']),
    biFaList: JSON.stringify(['朱雀临门', '贵人临身']),
  },
  {
    source: '大六壬高级预测学',
    question: '某女占婚姻是否幸福',
    askTime: '癸丑日酉时',
    eventType: '婚姻',
    lessonData: JSON.stringify({
      yearGanZhi: '癸丑', monthGanZhi: '乙卯', dayGanZhi: '癸丑',
      sanChuan: [{ chu: '未', zhong: '巳', mo: '卯' }],
    }),
    judgment: '干支上神相生，天后临支，青龙入传，婚姻美满。六合临三传，夫妻恩爱。三合课成，白头偕老。',
    verification: '婚后幸福，育有二子',
    keyPoints: JSON.stringify(['干支相生', '天后临支', '青龙入传', '六合临传']),
    keTi: '三合',
    tags: JSON.stringify(['婚姻', '幸福', '美满']),
    shenshaList: JSON.stringify(['天后', '青龙', '六合']),
    biFaList: JSON.stringify(['天后临日', '青龙入传', '干支相会']),
  },
  {
    source: '大六壬高级预测学',
    question: '某人占跳槽是否有利',
    askTime: '甲寅日巳时',
    eventType: '求财',
    lessonData: JSON.stringify({
      yearGanZhi: '甲寅', monthGanZhi: '丙辰', dayGanZhi: '甲寅',
      sanChuan: [{ chu: '巳', zhong: '卯', mo: '丑' }],
    }),
    judgment: '驿马发动临日干，变动之象。青龙临三传，新机会有利。德禄临身，跳槽后待遇提升。宜往东南。',
    verification: '跳槽后薪资翻倍',
    keyPoints: JSON.stringify(['驿马发动', '青龙入传', '德禄临身']),
    keTi: '元首',
    tags: JSON.stringify(['求财', '跳槽', '薪资翻倍']),
    shenshaList: JSON.stringify(['驿马', '青龙']),
    biFaList: JSON.stringify(['驿马发动', '青龙入传', '德禄临身']),
  },
  {
    source: '韦千里大六壬全集',
    question: '某人占一生财运走势',
    askTime: '乙卯日午时',
    eventType: '求财',
    lessonData: JSON.stringify({
      yearGanZhi: '乙卯', monthGanZhi: '丁巳', dayGanZhi: '乙卯',
      sanChuan: [{ chu: '未', zhong: '巳', mo: '卯' }],
    }),
    judgment: '青龙临初传，早年得财。中传太常，中年财运稳定。末传六合，晚年合作得财。一生财运上佳。',
    verification: '此人一生经商，富甲一方',
    keyPoints: JSON.stringify(['青龙初传', '太常中传', '六合末传']),
    keTi: '三传递生',
    tags: JSON.stringify(['求财', '一生', '富甲一方']),
    shenshaList: JSON.stringify(['青龙', '太常', '六合']),
    biFaList: JSON.stringify(['青龙入传', '太常喜庆', '三传递生']),
  },
  {
    source: '韦千里大六壬全集',
    question: '占某年天下大势',
    askTime: '丙辰日子时',
    eventType: '天时',
    lessonData: JSON.stringify({
      yearGanZhi: '丙辰', monthGanZhi: '戊午', dayGanZhi: '丙辰',
      sanChuan: [{ chu: '午', zhong: '辰', mo: '寅' }],
    }),
    judgment: '龙战课成，白虎临三传，天下有兵戈之象。太岁临日干，国家有大变动。返吟兼见，局势反复。',
    verification: '当年发生重大战事',
    keyPoints: JSON.stringify(['龙战课', '白虎临传', '太岁临干', '返吟兼见']),
    keTi: '龙战',
    tags: JSON.stringify(['天时', '大势', '兵戈']),
    shenshaList: JSON.stringify(['白虎', '太岁']),
    biFaList: JSON.stringify(['白虎入传']),
  },
  {
    source: '韦千里大六壬全集',
    question: '某人占寻访失散多年的亲人',
    askTime: '丁巳日寅时',
    eventType: '失物',
    lessonData: JSON.stringify({
      yearGanZhi: '丁巳', monthGanZhi: '己未', dayGanZhi: '丁巳',
      sanChuan: [{ chu: '申', zhong: '午', mo: '辰' }],
    }),
    judgment: '驿马发动临干，寻人必动。支上见六合临贵人，亲人在西南方。青龙临末传，终得团圆。',
    verification: '在西南某城寻得，一家团圆',
    keyPoints: JSON.stringify(['驿马发动', '六合', '贵人', '青龙末传']),
    keTi: '元首',
    tags: JSON.stringify(['失物', '寻人', '团圆']),
    shenshaList: JSON.stringify(['驿马', '六合', '贵人', '青龙']),
    biFaList: JSON.stringify(['驿马发动', '贵人临身', '青龙入传']),
  },
  {
    source: '韦千里大六壬全集',
    question: '占某人一生事业格局',
    askTime: '戊午日辰时',
    eventType: '考试',
    lessonData: JSON.stringify({
      yearGanZhi: '戊午', monthGanZhi: '庚申', dayGanZhi: '戊午',
      sanChuan: [{ chu: '巳', zhong: '卯', mo: '丑' }],
    }),
    judgment: '铸印课成，将星临身，贵格。青龙贵人俱临，一生仕途顺遂。三传递生，层层有人提拔。',
    verification: '此人官至尚书',
    keyPoints: JSON.stringify(['铸印课', '将星临身', '青龙贵人', '三传递生']),
    keTi: '铸印',
    tags: JSON.stringify(['考试', '仕途', '尚书']),
    shenshaList: JSON.stringify(['将星', '贵人', '青龙']),
    biFaList: JSON.stringify(['将星临身', '贵人临身', '青龙入传', '三传递生']),
  },
  {
    source: '韦千里大六壬全集',
    question: '占某日是否宜动土建宅',
    askTime: '己未日巳时',
    eventType: '田宅',
    lessonData: JSON.stringify({
      yearGanZhi: '己未', monthGanZhi: '辛酉', dayGanZhi: '己未',
      sanChuan: [{ chu: '丑', zhong: '亥', mo: '酉' }],
    }),
    judgment: '稼穑课成，太常临支，青龙入传，动土大吉。伏吟课兼见，建后安居。宜取辰时破土。',
    verification: '当日动土，建宅后家运兴旺',
    keyPoints: JSON.stringify(['稼穑课', '太常临支', '青龙入传', '伏吟兼见']),
    keTi: '稼穑',
    tags: JSON.stringify(['田宅', '动土', '兴旺']),
    shenshaList: JSON.stringify(['太常', '青龙']),
    biFaList: JSON.stringify(['太常喜庆', '青龙入传']),
  },
  {
    source: '韦千里大六壬全集',
    question: '占某妇人求子',
    askTime: '庚申日午时',
    eventType: '婚姻',
    lessonData: JSON.stringify({
      yearGanZhi: '庚申', monthGanZhi: '壬戌', dayGanZhi: '庚申',
      sanChuan: [{ chu: '子', zhong: '寅', mo: '辰' }],
    }),
    judgment: '天后临支上神，六合临三传，求子有望。青龙临初传，年内可得。三合课成，子女缘厚。',
    verification: '当年怀孕，次年得子',
    keyPoints: JSON.stringify(['天后临支', '六合临传', '青龙初传', '三合课']),
    keTi: '三合',
    tags: JSON.stringify(['婚姻', '求子', '得子']),
    shenshaList: JSON.stringify(['天后', '六合', '青龙']),
    biFaList: JSON.stringify(['天后临日', '青龙入传']),
  },
  {
    source: '韦千里大六壬全集',
    question: '某人占赴任途中吉凶',
    askTime: '辛酉日寅时',
    eventType: '出行',
    lessonData: JSON.stringify({
      yearGanZhi: '辛酉', monthGanZhi: '癸亥', dayGanZhi: '辛酉',
      sanChuan: [{ chu: '午', zhong: '辰', mo: '寅' }],
    }),
    judgment: '斩关课成，驿马青龙俱现，赴任顺利。但返吟兼见，途中或遇反复。白虎临驿马，注意路途安全。',
    verification: '途中遇雨耽搁三日，后平安到任',
    keyPoints: JSON.stringify(['斩关课', '驿马', '青龙', '返吟', '白虎']),
    keTi: '斩关',
    tags: JSON.stringify(['出行', '赴任', '波折']),
    shenshaList: JSON.stringify(['驿马', '青龙', '白虎']),
    biFaList: JSON.stringify(['驿马发动', '青龙入传', '白虎入传']),
  },
  {
    source: '韦千里大六壬全集',
    question: '某人占老母寿元',
    askTime: '壬戌日酉时',
    eventType: '疾病',
    lessonData: JSON.stringify({
      yearGanZhi: '壬戌', monthGanZhi: '甲子', dayGanZhi: '壬戌',
      sanChuan: [{ chu: '子', zhong: '戌', mo: '申' }],
    }),
    judgment: '白虎临支上神（支为母），鬼临三四，大凶。绝嗣课兼见，寿元将尽。宜准备后事。',
    verification: '三月后母亲去世',
    keyPoints: JSON.stringify(['白虎临支', '鬼临三四', '绝嗣课']),
    keTi: '绝嗣',
    tags: JSON.stringify(['疾病', '寿元', '去世']),
    shenshaList: JSON.stringify(['白虎']),
    biFaList: JSON.stringify(['鬼临三四', '白虎入传']),
  },
  {
    source: '韦千里大六壬全集',
    question: '占某书生科举前途',
    askTime: '癸亥日卯时',
    eventType: '考试',
    lessonData: JSON.stringify({
      yearGanZhi: '癸亥', monthGanZhi: '乙丑', dayGanZhi: '癸亥',
      sanChuan: [{ chu: '卯', zhong: '丑', mo: '亥' }],
    }),
    judgment: '元首课成，朱雀贵人俱临，科举必中。德禄临身，名次在前。将星临身，日后可为官。',
    verification: '中进士，后官至知府',
    keyPoints: JSON.stringify(['元首课', '朱雀', '贵人', '德禄临身', '将星临身']),
    keTi: '元首',
    tags: JSON.stringify(['考试', '科举', '进士']),
    shenshaList: JSON.stringify(['朱雀', '贵人', '将星']),
    biFaList: JSON.stringify(['朱雀临门', '贵人临身', '德禄临身', '将星临身']),
  },
  {
    source: '大六壬高级预测学',
    question: '某人占竞标一个大项目',
    askTime: '甲子日巳时',
    eventType: '求财',
    lessonData: JSON.stringify({
      yearGanZhi: '甲子', monthGanZhi: '丙寅', dayGanZhi: '甲子',
      sanChuan: [{ chu: '寅', zhong: '辰', mo: '午' }],
    }),
    judgment: '青龙临日干，六仪课成，竞标有利。干支上神相生，内部团结。三传递生，层层推进。中标可期。',
    verification: '中标，项目金额过亿',
    keyPoints: JSON.stringify(['青龙临干', '六仪课', '干支相生', '三传递生']),
    keTi: '六仪',
    tags: JSON.stringify(['求财', '竞标', '中标']),
    shenshaList: JSON.stringify(['青龙', '贵人']),
    biFaList: JSON.stringify(['青龙入传', '三传递生']),
  },
  {
    source: '大六壬高级预测学',
    question: '某艺人占签约新公司',
    askTime: '乙丑日午时',
    eventType: '合作',
    lessonData: JSON.stringify({
      yearGanZhi: '乙丑', monthGanZhi: '丁卯', dayGanZhi: '乙丑',
      sanChuan: [{ chu: '巳', zhong: '卯', mo: '丑' }],
    }),
    judgment: '干支上神六合，六合临传，签约顺利。但玄武临支上神，注意合同陷阱。青龙临末传，长远有利。',
    verification: '签约后发展顺利，但前期合同确有小陷阱',
    keyPoints: JSON.stringify(['干支六合', '六合临传', '玄武临支', '青龙末传']),
    keTi: '元首',
    tags: JSON.stringify(['合作', '签约', '长远有利']),
    shenshaList: JSON.stringify(['六合', '玄武', '青龙']),
    biFaList: JSON.stringify(['干支相会', '玄武入课', '青龙入传']),
  },
  {
    source: '大六壬高级预测学',
    question: '某人占出国移民是否可行',
    askTime: '丙寅日申时',
    eventType: '出行',
    lessonData: JSON.stringify({
      yearGanZhi: '丙寅', monthGanZhi: '戊辰', dayGanZhi: '丙寅',
      sanChuan: [{ chu: '申', zhong: '戌', mo: '子' }],
    }),
    judgment: '驿马发动临申（申为西南，主欧美），斩关课成，移民可成。但魁度天门，签证流程漫长。',
    verification: '两年后移民成功',
    keyPoints: JSON.stringify(['驿马发动', '斩关课', '魁度天门']),
    keTi: '斩关',
    tags: JSON.stringify(['出行', '移民', '漫长']),
    shenshaList: JSON.stringify(['驿马']),
    biFaList: JSON.stringify(['驿马发动', '魁度天门']),
  },
  {
    source: '大六壬高级预测学',
    question: '某人占癌症治疗效果',
    askTime: '丁卯日酉时',
    eventType: '疾病',
    lessonData: JSON.stringify({
      yearGanZhi: '丁卯', monthGanZhi: '己巳', dayGanZhi: '丁卯',
      sanChuan: [{ chu: '酉', zhong: '未', mo: '巳' }],
    }),
    judgment: '白虎临日干，鬼临三四，度厄课成，病势凶险。然贵人临末传，有名医可救。宜往北方就医。',
    verification: '往北京就医，治疗后病情稳定',
    keyPoints: JSON.stringify(['白虎临干', '鬼临三四', '度厄课', '贵人末传']),
    keTi: '度厄',
    tags: JSON.stringify(['疾病', '癌症', '稳定']),
    shenshaList: JSON.stringify(['白虎', '贵人']),
    biFaList: JSON.stringify(['白虎入传', '鬼临三四', '贵人临身']),
  },
  {
    source: '大六壬高级预测学',
    question: '某人占购房时机',
    askTime: '戊辰日巳时',
    eventType: '田宅',
    lessonData: JSON.stringify({
      yearGanZhi: '戊辰', monthGanZhi: '庚午', dayGanZhi: '戊辰',
      sanChuan: [{ chu: '未', zhong: '巳', mo: '卯' }],
    }),
    judgment: '太常临支上神，青龙临三传，购房时机成熟。稼穑课兼见，田宅大利。宜在本月内出手。',
    verification: '当月购房，三年后房价翻倍',
    keyPoints: JSON.stringify(['太常临支', '青龙临传', '稼穑课']),
    keTi: '稼穑',
    tags: JSON.stringify(['田宅', '购房', '翻倍']),
    shenshaList: JSON.stringify(['太常', '青龙']),
    biFaList: JSON.stringify(['太常喜庆', '青龙入传']),
  },
  {
    source: '大六壬高级预测学',
    question: '某人占创业方向选择',
    askTime: '己巳日辰时',
    eventType: '求财',
    lessonData: JSON.stringify({
      yearGanZhi: '己巳', monthGanZhi: '辛未', dayGanZhi: '己巳',
      sanChuan: [{ chu: '酉', zhong: '未', mo: '巳' }],
    }),
    judgment: '斫轮课成，青龙临三传，创业大利。宜选择技术、创新方向。末传巳火，宜互联网或科技行业。',
    verification: '创办科技公司，三年后上市',
    keyPoints: JSON.stringify(['斫轮课', '青龙临传', '末传巳火']),
    keTi: '斫轮',
    tags: JSON.stringify(['求财', '创业', '科技']),
    shenshaList: JSON.stringify(['青龙']),
    biFaList: JSON.stringify(['青龙入传']),
  },
  {
    source: '大六壬高级预测学',
    question: '某人占被诬告后清白能否得证',
    askTime: '庚午日申时',
    eventType: '官非',
    lessonData: JSON.stringify({
      yearGanZhi: '庚午', monthGanZhi: '壬申', dayGanZhi: '庚午',
      sanChuan: [{ chu: '子', zhong: '戌', mo: '申' }],
    }),
    judgment: '贵人临日干，干上神克勾陈，清白可得证。朱雀临三传，文书证据有利。但过程漫长，需耐心。',
    verification: '一年后终得清白',
    keyPoints: JSON.stringify(['贵人临干', '干克勾陈', '朱雀临传']),
    keTi: '涉害',
    tags: JSON.stringify(['官非', '诬告', '清白']),
    shenshaList: JSON.stringify(['贵人', '勾陈', '朱雀']),
    biFaList: JSON.stringify(['贵人临身', '朱雀临门']),
  },
  {
    source: '大六壬高级预测学',
    question: '某人占换城市发展吉凶',
    askTime: '辛未日寅时',
    eventType: '出行',
    lessonData: JSON.stringify({
      yearGanZhi: '辛未', monthGanZhi: '癸酉', dayGanZhi: '辛未',
      sanChuan: [{ chu: '寅', zhong: '子', mo: '戌' }],
    }),
    judgment: '驿马发动临干，变动在即。青龙临驿马，变动有利。宜往东方城市。游子课成，适应新环境需时日。',
    verification: '搬到上海，一年后事业起飞',
    keyPoints: JSON.stringify(['驿马发动', '青龙临驿马', '游子课']),
    keTi: '游子',
    tags: JSON.stringify(['出行', '换城市', '起飞']),
    shenshaList: JSON.stringify(['驿马', '青龙']),
    biFaList: JSON.stringify(['驿马发动', '青龙入传']),
  },
  {
    source: '大六壬高级预测学',
    question: '某人占孩子考大学志愿填报',
    askTime: '壬申日辰时',
    eventType: '考试',
    lessonData: JSON.stringify({
      yearGanZhi: '壬申', monthGanZhi: '甲戌', dayGanZhi: '壬申',
      sanChuan: [{ chu: '卯', zhong: '丑', mo: '亥' }],
    }),
    judgment: '朱雀临干上神，文笔尚佳。贵人临三传，有人指点志愿。德禄临身，终被理想学校录取。宜报北方院校。',
    verification: '被北京某985高校录取',
    keyPoints: JSON.stringify(['朱雀临干', '贵人临传', '德禄临身']),
    keTi: '元首',
    tags: JSON.stringify(['考试', '志愿', '985']),
    shenshaList: JSON.stringify(['朱雀', '贵人']),
    biFaList: JSON.stringify(['朱雀临门', '贵人临身', '德禄临身']),
  },
  {
    source: '大六壬高级预测学',
    question: '某人占丢失手机能否找回',
    askTime: '癸酉日亥时',
    eventType: '失物',
    lessonData: JSON.stringify({
      yearGanZhi: '癸酉', monthGanZhi: '乙亥', dayGanZhi: '癸酉',
      sanChuan: [{ chu: '亥', zhong: '丑', mo: '卯' }],
    }),
    judgment: '玄武临日干，确为被盗。天空临支上神，失物已空。闭口课成，寻回希望渺茫。建议报警备案。',
    verification: '报警后未找回',
    keyPoints: JSON.stringify(['玄武临干', '天空临支', '闭口课']),
    keTi: '闭口',
    tags: JSON.stringify(['失物', '未寻回', '被盗']),
    shenshaList: JSON.stringify(['玄武', '天空']),
    biFaList: JSON.stringify(['玄武入课', '天空无成']),
  },
  {
    source: '六壬断案详解',
    question: '某商人占与外商合作进口贸易',
    askTime: '甲戌日午时',
    eventType: '合作',
    lessonData: JSON.stringify({
      yearGanZhi: '甲戌', monthGanZhi: '丙子', dayGanZhi: '甲戌',
      sanChuan: [{ chu: '午', zhong: '辰', mo: '寅' }],
    }),
    judgment: '干支上神相生，六合临传，合作基础好。但支上见玄武，外商有隐情。青龙临末传，长期有利。建议签短约试水。',
    verification: '先签一年短约，后合作愉快续签五年',
    keyPoints: JSON.stringify(['干支相生', '六合临传', '玄武临支', '青龙末传']),
    keTi: '元首',
    tags: JSON.stringify(['合作', '外贸', '试水成功']),
    shenshaList: JSON.stringify(['六合', '玄武', '青龙']),
    biFaList: JSON.stringify(['干支相会', '玄武入课', '青龙入传']),
  },
  {
    source: '六壬断案详解',
    question: '某人占祖坟是否需迁葬',
    askTime: '乙亥日巳时',
    eventType: '田宅',
    lessonData: JSON.stringify({
      yearGanZhi: '乙亥', monthGanZhi: '丁丑', dayGanZhi: '乙亥',
      sanChuan: [{ chu: '丑', zhong: '亥', mo: '酉' }],
    }),
    judgment: '勾陈临支上神克干，祖坟确有问题。白虎临支下神，阴宅犯煞。返吟课成，宜迁不宜守。择吉日迁葬。',
    verification: '迁葬后家运明显好转',
    keyPoints: JSON.stringify(['勾陈克干', '白虎临支下', '返吟课']),
    keTi: '返吟',
    tags: JSON.stringify(['田宅', '祖坟', '迁葬']),
    shenshaList: JSON.stringify(['勾陈', '白虎']),
    biFaList: JSON.stringify(['勾陈临日', '白虎入传']),
  },
  {
    source: '六壬断案详解',
    question: '占某年旱涝情况',
    askTime: '丙子日卯时',
    eventType: '天时',
    lessonData: JSON.stringify({
      yearGanZhi: '丙子', monthGanZhi: '戊寅', dayGanZhi: '丙子',
      sanChuan: [{ chu: '辰', zhong: '午', mo: '申' }],
    }),
    judgment: '青龙临三传，天后亦现，今年雨水充沛。朱雀不显，晴天偏少。稼穑课成，农业丰收可期。',
    verification: '当年风调雨顺，农业丰收',
    keyPoints: JSON.stringify(['青龙临传', '天后临传', '稼穑课']),
    keTi: '稼穑',
    tags: JSON.stringify(['天时', '丰收', '风调雨顺']),
    shenshaList: JSON.stringify(['青龙', '天后']),
    biFaList: JSON.stringify([]),
  },
  {
    source: '六壬断案详解',
    question: '某人占与上司关系如何改善',
    askTime: '丁丑日申时',
    eventType: '合作',
    lessonData: JSON.stringify({
      yearGanZhi: '丁丑', monthGanZhi: '己卯', dayGanZhi: '丁丑',
      sanChuan: [{ chu: '酉', zhong: '未', mo: '巳' }],
    }),
    judgment: '干上神克支上神，与上司（支）关系紧张。贵人不临干，缺乏支持。但将星临干，自身有实力。宜低调做事。',
    verification: '低调半年后，上司态度转变',
    keyPoints: JSON.stringify(['干克支', '贵人不临', '将星临干']),
    keTi: '重审',
    tags: JSON.stringify(['合作', '上司', '改善']),
    shenshaList: JSON.stringify(['将星']),
    biFaList: JSON.stringify(['将星临身']),
  },
  {
    source: '六壬断案详解',
    question: '某人占店铺选址何方为宜',
    askTime: '戊寅日巳时',
    eventType: '田宅',
    lessonData: JSON.stringify({
      yearGanZhi: '戊寅', monthGanZhi: '庚辰', dayGanZhi: '戊寅',
      sanChuan: [{ chu: '午', zhong: '辰', mo: '寅' }],
    }),
    judgment: '太常临支上神在午方（正南），青龙临三传，正南为佳。驿马在寅（东北），亦可考虑。建议正南为主。',
    verification: '在正南街开店，生意兴隆',
    keyPoints: JSON.stringify(['太常临午', '青龙临传', '驿马在寅']),
    keTi: '元首',
    tags: JSON.stringify(['田宅', '选址', '正南']),
    shenshaList: JSON.stringify(['太常', '青龙', '驿马']),
    biFaList: JSON.stringify(['太常喜庆', '青龙入传']),
  },
  {
    source: '六壬断案详解',
    question: '占某人是否宜远行经商',
    askTime: '己卯日寅时',
    eventType: '出行',
    lessonData: JSON.stringify({
      yearGanZhi: '己卯', monthGanZhi: '辛巳', dayGanZhi: '己卯',
      sanChuan: [{ chu: '申', zhong: '午', mo: '辰' }],
    }),
    judgment: '驿马青龙俱现，远行经商大利。轩盖课成，出行风光。宜往西南方向，大利。',
    verification: '往西南经商，获利颇丰',
    keyPoints: JSON.stringify(['驿马', '青龙', '轩盖课']),
    keTi: '轩盖',
    tags: JSON.stringify(['出行', '经商', '大利']),
    shenshaList: JSON.stringify(['驿马', '青龙']),
    biFaList: JSON.stringify(['驿马发动', '青龙入传']),
  },
  {
    source: '六壬断案详解',
    question: '某人占自己寿元',
    askTime: '庚辰日酉时',
    eventType: '疾病',
    lessonData: JSON.stringify({
      yearGanZhi: '庚辰', monthGanZhi: '壬午', dayGanZhi: '庚辰',
      sanChuan: [{ chu: '戌', zhong: '申', mo: '午' }],
    }),
    judgment: '白虎临日干，度厄课成，大凶。三传皆克日干，寿元不久。绝嗣兼见，子孙缘薄。宜及时行善积德。',
    verification: '两年后病逝',
    keyPoints: JSON.stringify(['白虎临干', '度厄课', '三传克干', '绝嗣']),
    keTi: '度厄',
    tags: JSON.stringify(['疾病', '寿元', '病逝']),
    shenshaList: JSON.stringify(['白虎']),
    biFaList: JSON.stringify(['白虎入传']),
  },
  {
    source: '六壬神课金口诀现代实例精解',
    question: '某人占当日出行吉凶（金口诀）',
    askTime: '辛巳日卯时',
    eventType: '出行',
    lessonData: JSON.stringify({
      method: 'jin_kou_jue',
      diFen: '卯', yueJiang: '青龙寅', guiShen: '驿马寅', renYuan: '乙',
      keTi: '神将同宫',
    }),
    judgment: '神将同宫临青龙驿马，出行大吉。方生将，根基稳固。四位纯阳，出行明朗顺利。宜早出发。',
    verification: '当日出行一切顺利',
    keyPoints: JSON.stringify(['神将同宫', '青龙驿马', '方生将', '四位纯阳']),
    keTi: '神将同宫',
    tags: JSON.stringify(['出行', '金口诀', '顺利']),
    shenshaList: JSON.stringify(['青龙', '驿马']),
    biFaList: JSON.stringify([]),
  },
  {
    source: '六壬神课金口诀现代实例精解',
    question: '某人占竞聘岗位（金口诀）',
    askTime: '壬午日巳时',
    eventType: '考试',
    lessonData: JSON.stringify({
      method: 'jin_kou_jue',
      diFen: '巳', yueJiang: '朱雀午', guiShen: '贵人丑', renYuan: '丁',
      keTi: '神生将',
    }),
    judgment: '神生将，贵人生朱雀，上级赏识。朱雀临将，口才出众面试加分。人元生地分，根基扎实。竞聘必成。',
    verification: '竞聘成功，升为部门经理',
    keyPoints: JSON.stringify(['神生将', '贵人生朱雀', '朱雀临将', '人元生地分']),
    keTi: '神生将',
    tags: JSON.stringify(['考试', '竞聘', '成功']),
    shenshaList: JSON.stringify(['贵人', '朱雀']),
    biFaList: JSON.stringify([]),
  },
  {
    source: '六壬神课金口诀现代实例精解',
    question: '某人占失窃后小偷方位（金口诀）',
    askTime: '癸未日戌时',
    eventType: '失物',
    lessonData: JSON.stringify({
      method: 'jin_kou_jue',
      diFen: '戌', yueJiang: '玄武子', guiShen: '白虎申', renYuan: '壬',
      keTi: '干克神',
    }),
    judgment: '玄武临将，确为盗贼。白虎临神，盗贼凶悍。干克神，主动可擒。方为戌（西北），贼往西北逃窜。速报官。',
    verification: '报警后在西北方向抓获小偷',
    keyPoints: JSON.stringify(['玄武临将', '白虎临神', '干克神', '地分戌']),
    keTi: '干克神',
    tags: JSON.stringify(['失物', '小偷', '西北']),
    shenshaList: JSON.stringify(['玄武', '白虎']),
    biFaList: JSON.stringify([]),
  },
  {
    source: '六壬神课金口诀现代实例精解',
    question: '某人占项目投资回报（金口诀）',
    askTime: '甲申日午时',
    eventType: '求财',
    lessonData: JSON.stringify({
      method: 'jin_kou_jue',
      diFen: '午', yueJiang: '天空戌', guiShen: '玄武子', renYuan: '丙',
      keTi: '将克方',
    }),
    judgment: '天空临将，玄武临神，项目虚多实少。将克方，根基不稳。干克将，主动可止损。建议放弃。',
    verification: '未投资，后该项目暴雷',
    keyPoints: JSON.stringify(['天空临将', '玄武临神', '将克方', '干克将']),
    keTi: '将克方',
    tags: JSON.stringify(['求财', '骗局', '放弃']),
    shenshaList: JSON.stringify(['天空', '玄武']),
    biFaList: JSON.stringify([]),
  },
  {
    source: '六壬神课金口诀现代实例精解',
    question: '某人占母亲病况（金口诀）',
    askTime: '乙酉日酉时',
    eventType: '疾病',
    lessonData: JSON.stringify({
      method: 'jin_kou_jue',
      diFen: '酉', yueJiang: '白虎申', guiShen: '太阴酉', renYuan: '辛',
      keTi: '四位纯阴',
    }),
    judgment: '白虎临将，病势不轻。四位纯阴，病情隐蔽难查。神将比和，病情稳定。将生方，根基尚存。建议住院详查。',
    verification: '住院详查后发现隐藏疾病，及时治疗',
    keyPoints: JSON.stringify(['白虎临将', '四位纯阴', '神将比和', '将生方']),
    keTi: '四位纯阴',
    tags: JSON.stringify(['疾病', '母病', '及时治疗']),
    shenshaList: JSON.stringify(['白虎', '太阴']),
    biFaList: JSON.stringify([]),
  },
  {
    source: '六壬神课金口诀现代实例精解',
    question: '某人占女友是否真心（金口诀）',
    askTime: '丙戌日午时',
    eventType: '婚姻',
    lessonData: JSON.stringify({
      method: 'jin_kou_jue',
      diFen: '午', yueJiang: '天后子', guiShen: '玄武亥', renYuan: '丙',
      keTi: '神克将',
    }),
    judgment: '天后临将本吉，但玄武临神克将，女方有隐情。神克将，贵人不助。干克神，可主动追问。建议坦诚沟通。',
    verification: '坦诚沟通后，女友坦白曾隐瞒过往',
    keyPoints: JSON.stringify(['天后临将', '玄武克将', '神克将']),
    keTi: '神克将',
    tags: JSON.stringify(['婚姻', '隐情', '沟通']),
    shenshaList: JSON.stringify(['天后', '玄武']),
    biFaList: JSON.stringify([]),
  },
  {
    source: '大六壬详解函授讲义',
    question: '某人占调动工作可否',
    askTime: '丁亥日巳时',
    eventType: '求财',
    lessonData: JSON.stringify({
      yearGanZhi: '丁亥', monthGanZhi: '己丑', dayGanZhi: '丁亥',
      sanChuan: [{ chu: '午', zhong: '辰', mo: '寅' }],
    }),
    judgment: '驿马临日干，调动之象。青龙临三传，新岗位有利。贵人临末传，调动有人相助。宜主动申请。',
    verification: '主动申请后成功调岗，薪资提升',
    keyPoints: JSON.stringify(['驿马临干', '青龙临传', '贵人末传']),
    keTi: '元首',
    tags: JSON.stringify(['求财', '调动', '加薪']),
    shenshaList: JSON.stringify(['驿马', '青龙', '贵人']),
    biFaList: JSON.stringify(['驿马发动', '青龙入传', '贵人临身']),
  },
  {
    source: '大六壬详解函授讲义',
    question: '某人占离婚官司子女归属',
    askTime: '戊子日申时',
    eventType: '官非',
    lessonData: JSON.stringify({
      yearGanZhi: '戊子', monthGanZhi: '庚寅', dayGanZhi: '戊子',
      sanChuan: [{ chu: '亥', zhong: '丑', mo: '卯' }],
    }),
    judgment: '勾陈朱雀俱临，离婚官司难免。支上见六合临贵人，子女归属有利。但返吟课成，过程反复。',
    verification: '官司打了半年，最终子女归女方',
    keyPoints: JSON.stringify(['勾陈', '朱雀', '六合', '贵人', '返吟']),
    keTi: '返吟',
    tags: JSON.stringify(['官非', '离婚', '子女']),
    shenshaList: JSON.stringify(['勾陈', '朱雀', '六合', '贵人']),
    biFaList: JSON.stringify(['朱雀临门', '勾陈临日', '贵人临身']),
  },
  {
    source: '大六壬详解函授讲义',
    question: '某人占股票投资方向',
    askTime: '己丑日辰时',
    eventType: '求财',
    lessonData: JSON.stringify({
      yearGanZhi: '己丑', monthGanZhi: '辛卯', dayGanZhi: '己丑',
      sanChuan: [{ chu: '卯', zhong: '巳', mo: '未' }],
    }),
    judgment: '青龙临初传在卯（东方/木），宜投东方产业、绿色能源。财星在三传，今年有行情。但末传空亡，年底需出货。',
    verification: '投资新能源股票，上半年大赚，年底回调前出货',
    keyPoints: JSON.stringify(['青龙临卯', '财星三传', '末传空亡']),
    keTi: '三合',
    tags: JSON.stringify(['求财', '股票', '新能源']),
    shenshaList: JSON.stringify(['青龙']),
    biFaList: JSON.stringify(['青龙入传', '三传空亡']),
  },
  {
    source: '大六壬详解函授讲义',
    question: '某人占儿子高考志愿',
    askTime: '庚寅日卯时',
    eventType: '考试',
    lessonData: JSON.stringify({
      yearGanZhi: '庚寅', monthGanZhi: '壬辰', dayGanZhi: '庚寅',
      sanChuan: [{ chu: '巳', zhong: '卯', mo: '丑' }],
    }),
    judgment: '朱雀临干，文笔不错。斫轮课成，宜报理工科。德禄临身在丑方（东北），宜报东北方向院校。',
    verification: '被东北某工科强校录取',
    keyPoints: JSON.stringify(['朱雀临干', '斫轮课', '德禄在丑']),
    keTi: '斫轮',
    tags: JSON.stringify(['考试', '高考', '工科']),
    shenshaList: JSON.stringify(['朱雀']),
    biFaList: JSON.stringify(['朱雀临门', '德禄临身']),
  },
  {
    source: '大六壬详解函授讲义',
    question: '某人占岳父病情',
    askTime: '辛卯日酉时',
    eventType: '疾病',
    lessonData: JSON.stringify({
      yearGanZhi: '辛卯', monthGanZhi: '癸巳', dayGanZhi: '辛卯',
      sanChuan: [{ chu: '子', zhong: '戌', mo: '申' }],
    }),
    judgment: '白虎临支（支为岳家），病势不轻。鬼临三四，病情复杂。然青龙临末传，手术可救。建议西医手术。',
    verification: '手术后康复良好',
    keyPoints: JSON.stringify(['白虎临支', '鬼临三四', '青龙末传']),
    keTi: '涉害',
    tags: JSON.stringify(['疾病', '岳父', '手术成功']),
    shenshaList: JSON.stringify(['白虎', '青龙']),
    biFaList: JSON.stringify(['白虎入传', '鬼临三四']),
  },
  {
    source: '大六壬详解函授讲义',
    question: '某人占乡下老宅是否该卖',
    askTime: '壬辰日巳时',
    eventType: '田宅',
    lessonData: JSON.stringify({
      yearGanZhi: '壬辰', monthGanZhi: '甲午', dayGanZhi: '壬辰',
      sanChuan: [{ chu: '未', zhong: '巳', mo: '卯' }],
    }),
    judgment: '太常临支，青龙入传，老宅风水尚佳。稼穑课成，田宅不宜轻卖。天空临三传，卖了可能后悔。建议保留。',
    verification: '保留老宅，三年后拆迁补偿丰厚',
    keyPoints: JSON.stringify(['太常临支', '青龙入传', '稼穑课', '天空临传']),
    keTi: '稼穑',
    tags: JSON.stringify(['田宅', '老宅', '保留']),
    shenshaList: JSON.stringify(['太常', '青龙', '天空']),
    biFaList: JSON.stringify(['太常喜庆', '青龙入传']),
  },
  {
    source: '大六壬详解函授讲义',
    question: '某人占妻子是否适合开店',
    askTime: '癸巳日午时',
    eventType: '求财',
    lessonData: JSON.stringify({
      yearGanZhi: '癸巳', monthGanZhi: '乙未', dayGanZhi: '癸巳',
      sanChuan: [{ chu: '午', zhong: '辰', mo: '寅' }],
    }),
    judgment: '青龙临日干，太常临支（支为妻），开店大利。六合临三传，合作客源不断。宜开餐饮或服装店。',
    verification: '开服装店，生意兴隆',
    keyPoints: JSON.stringify(['青龙临干', '太常临支', '六合临传']),
    keTi: '元首',
    tags: JSON.stringify(['求财', '开店', '兴隆']),
    shenshaList: JSON.stringify(['青龙', '太常', '六合']),
    biFaList: JSON.stringify(['青龙入传', '太常喜庆']),
  },
  {
    source: '大六壬详解函授讲义',
    question: '某人占侄儿在外安全',
    askTime: '甲午日申时',
    eventType: '出行',
    lessonData: JSON.stringify({
      yearGanZhi: '甲午', monthGanZhi: '丙申', dayGanZhi: '甲午',
      sanChuan: [{ chu: '子', zhong: '戌', mo: '申' }],
    }),
    judgment: '驿马临干但白虎亦临驿马，人在外但有风险。朱雀临三传，近日应有消息。青龙在末传，最终平安。',
    verification: '三日后侄儿来电报平安',
    keyPoints: JSON.stringify(['驿马临干', '白虎临驿马', '朱雀临传', '青龙末传']),
    keTi: '涉害',
    tags: JSON.stringify(['出行', '安全', '平安']),
    shenshaList: JSON.stringify(['驿马', '白虎', '朱雀', '青龙']),
    biFaList: JSON.stringify(['驿马发动', '白虎入传', '青龙入传']),
  },
  {
    source: '大六壬详解函授讲义',
    question: '某人占弟弟官司能否和解',
    askTime: '乙未日酉时',
    eventType: '官非',
    lessonData: JSON.stringify({
      yearGanZhi: '乙未', monthGanZhi: '丁酉', dayGanZhi: '乙未',
      sanChuan: [{ chu: '戌', zhong: '申', mo: '午' }],
    }),
    judgment: '贵人临支（支为弟），官司有人相助。六合临三传，和解有望。勾陈不克日干，官方态度缓和。建议主动和解。',
    verification: '主动提出和解，对方接受',
    keyPoints: JSON.stringify(['贵人临支', '六合临传', '勾陈不克干']),
    keTi: '知一',
    tags: JSON.stringify(['官非', '和解', '成功']),
    shenshaList: JSON.stringify(['贵人', '六合', '勾陈']),
    biFaList: JSON.stringify(['贵人临身']),
  },
  {
    source: '大六壬详解函授讲义',
    question: '某人占出国读博申请',
    askTime: '丙申日辰时',
    eventType: '考试',
    lessonData: JSON.stringify({
      yearGanZhi: '丙申', monthGanZhi: '戊戌', dayGanZhi: '丙申',
      sanChuan: [{ chu: '巳', zhong: '卯', mo: '丑' }],
    }),
    judgment: '朱雀临干，文书有利。驿马在申（申为西南，主欧美），出国可成。魁度天门，签证关卡需耐心。斫轮课成，学术突破。',
    verification: '获美国名校全奖录取',
    keyPoints: JSON.stringify(['朱雀临干', '驿马在申', '魁度天门', '斫轮课']),
    keTi: '斫轮',
    tags: JSON.stringify(['考试', '留学', '全奖']),
    shenshaList: JSON.stringify(['朱雀', '驿马']),
    biFaList: JSON.stringify(['朱雀临门', '驿马发动', '魁度天门']),
  },
  {
    source: '大六壬详解函授讲义',
    question: '某人占公司搬迁选址',
    askTime: '丁酉日巳时',
    eventType: '田宅',
    lessonData: JSON.stringify({
      yearGanZhi: '丁酉', monthGanZhi: '己亥', dayGanZhi: '丁酉',
      sanChuan: [{ chu: '未', zhong: '巳', mo: '卯' }],
    }),
    judgment: '太常临支上神在未方（西南），青龙临三传，西南方向为佳。驿马在巳（东南），东南亦可考虑。首选西南。',
    verification: '搬至西南某写字楼，公司发展顺利',
    keyPoints: JSON.stringify(['太常在未', '青龙临传', '驿马在巳']),
    keTi: '元首',
    tags: JSON.stringify(['田宅', '搬迁', '西南']),
    shenshaList: JSON.stringify(['太常', '青龙', '驿马']),
    biFaList: JSON.stringify(['太常喜庆', '青龙入传']),
  },
  {
    source: '大六壬详解函授讲义',
    question: '某人占失踪老人能否找到',
    askTime: '戊戌日子时',
    eventType: '失物',
    lessonData: JSON.stringify({
      yearGanZhi: '戊戌', monthGanZhi: '庚子', dayGanZhi: '戊戌',
      sanChuan: [{ chu: '寅', zhong: '子', mo: '戌' }],
    }),
    judgment: '驿马临日干，老人已走动。支上见六合临贵人，有贵人相助寻找。末传见青龙，终得团圆。宜往东北方向寻找。',
    verification: '在东北方向某养老院找到',
    keyPoints: JSON.stringify(['驿马临干', '六合贵人', '青龙末传']),
    keTi: '元首',
    tags: JSON.stringify(['失物', '寻人', '找到']),
    shenshaList: JSON.stringify(['驿马', '六合', '贵人', '青龙']),
    biFaList: JSON.stringify(['驿马发动', '贵人临身', '青龙入传']),
  },
  {
    source: '六壬神课吉凶正断法',
    question: '某人占辞职创业时机',
    askTime: '己亥日午时',
    eventType: '求财',
    lessonData: JSON.stringify({
      yearGanZhi: '己亥', monthGanZhi: '辛丑', dayGanZhi: '己亥',
      sanChuan: [{ chu: '卯', zhong: '巳', mo: '未' }],
    }),
    judgment: '驿马临日干，变动时机已到。青龙临三传，创业有利。斫轮课成，宜技术创新方向。本月即可行动。',
    verification: '辞职创业，两年后公司估值过亿',
    keyPoints: JSON.stringify(['驿马临干', '青龙临传', '斫轮课']),
    keTi: '斫轮',
    tags: JSON.stringify(['求财', '创业', '估值过亿']),
    shenshaList: JSON.stringify(['驿马', '青龙']),
    biFaList: JSON.stringify(['驿马发动', '青龙入传']),
  },
  {
    source: '六壬神课吉凶正断法',
    question: '某人占邻居纠纷如何解决',
    askTime: '庚子日酉时',
    eventType: '官非',
    lessonData: JSON.stringify({
      yearGanZhi: '庚子', monthGanZhi: '壬寅', dayGanZhi: '庚子',
      sanChuan: [{ chu: '辰', zhong: '寅', mo: '子' }],
    }),
    judgment: '朱雀临门，口舌难免。勾陈临支，纠纷涉及田土。贵人临末传，调解有望。宜请社区调解。',
    verification: '社区调解成功，双方和解',
    keyPoints: JSON.stringify(['朱雀临门', '勾陈临支', '贵人末传']),
    keTi: '元首',
    tags: JSON.stringify(['官非', '邻居', '调解']),
    shenshaList: JSON.stringify(['朱雀', '勾陈', '贵人']),
    biFaList: JSON.stringify(['朱雀临门', '勾陈临日', '贵人临身']),
  },
  {
    source: '六壬神课吉凶正断法',
    question: '某人占自驾游是否安全',
    askTime: '辛丑日寅时',
    eventType: '出行',
    lessonData: JSON.stringify({
      yearGanZhi: '辛丑', monthGanZhi: '癸卯', dayGanZhi: '辛丑',
      sanChuan: [{ chu: '午', zhong: '辰', mo: '寅' }],
    }),
    judgment: '驿马青龙俱现，出行顺利。但白虎临驿马，路途注意安全驾驶。青龙临末传，最终平安抵达。',
    verification: '自驾顺利，全程平安',
    keyPoints: JSON.stringify(['驿马', '青龙', '白虎临驿马']),
    keTi: '元首',
    tags: JSON.stringify(['出行', '自驾', '平安']),
    shenshaList: JSON.stringify(['驿马', '青龙', '白虎']),
    biFaList: JSON.stringify(['驿马发动', '青龙入传', '白虎入传']),
  },
  {
    source: '六壬神课吉凶正断法',
    question: '某人占妻子怀孕是否顺利',
    askTime: '壬寅日巳时',
    eventType: '疾病',
    lessonData: JSON.stringify({
      yearGanZhi: '壬寅', monthGanZhi: '甲辰', dayGanZhi: '壬寅',
      sanChuan: [{ chu: '卯', zhong: '丑', mo: '亥' }],
    }),
    judgment: '天后临支（支为妻），六合临三传，怀孕顺利。青龙临末传，生产平安。三合课成，母子平安。',
    verification: '顺利生产，母子平安',
    keyPoints: JSON.stringify(['天后临支', '六合临传', '青龙末传', '三合课']),
    keTi: '三合',
    tags: JSON.stringify(['疾病', '怀孕', '平安']),
    shenshaList: JSON.stringify(['天后', '六合', '青龙']),
    biFaList: JSON.stringify(['天后临日', '青龙入传']),
  },
  {
    source: '六壬神课吉凶正断法',
    question: '某人占考公务员面试',
    askTime: '癸卯日辰时',
    eventType: '考试',
    lessonData: JSON.stringify({
      yearGanZhi: '癸卯', monthGanZhi: '乙巳', dayGanZhi: '癸卯',
      sanChuan: [{ chu: '巳', zhong: '卯', mo: '丑' }],
    }),
    judgment: '贵人临日干，面试有贵人相助。朱雀临三传，口才发挥出色。铸印课成，公务员可成。宜着正装。',
    verification: '面试通过，考上公务员',
    keyPoints: JSON.stringify(['贵人临干', '朱雀临传', '铸印课']),
    keTi: '铸印',
    tags: JSON.stringify(['考试', '公务员', '通过']),
    shenshaList: JSON.stringify(['贵人', '朱雀']),
    biFaList: JSON.stringify(['贵人临身', '朱雀临门']),
  },
  {
    source: '六壬神课吉凶正断法',
    question: '某人占捡到钱包如何处理',
    askTime: '甲辰日亥时',
    eventType: '失物',
    lessonData: JSON.stringify({
      yearGanZhi: '甲辰', monthGanZhi: '丙午', dayGanZhi: '甲辰',
      sanChuan: [{ chu: '子', zhong: '戌', mo: '申' }],
    }),
    judgment: '玄武临日干但被贵人克制，非盗窃之物。支上见财星临贵人，失主为有身份之人。青龙临末传，归还后有好报。建议归还。',
    verification: '归还失主后，失主竟是公司董事长，后获提拔',
    keyPoints: JSON.stringify(['玄武被克', '财星临贵人', '青龙末传']),
    keTi: '元首',
    tags: JSON.stringify(['失物', '归还', '好报']),
    shenshaList: JSON.stringify(['玄武', '贵人', '青龙']),
    biFaList: JSON.stringify(['贵人临身', '青龙入传']),
  },
  {
    source: '六壬神课吉凶正断法',
    question: '某人占与同事合作项目',
    askTime: '乙巳日午时',
    eventType: '合作',
    lessonData: JSON.stringify({
      yearGanZhi: '乙巳', monthGanZhi: '丁未', dayGanZhi: '乙巳',
      sanChuan: [{ chu: '未', zhong: '巳', mo: '卯' }],
    }),
    judgment: '干支上神比和，合作默契。六合临三传，团队和谐。三传递生，项目层层推进。成功可期。',
    verification: '项目顺利完成，两人均获嘉奖',
    keyPoints: JSON.stringify(['干支比和', '六合临传', '三传递生']),
    keTi: '三传递生',
    tags: JSON.stringify(['合作', '项目', '成功']),
    shenshaList: JSON.stringify(['六合']),
    biFaList: JSON.stringify(['三传递生']),
  },
  {
    source: '六壬神课吉凶正断法',
    question: '某人占祖宅是否该翻修',
    askTime: '丙午日巳时',
    eventType: '田宅',
    lessonData: JSON.stringify({
      yearGanZhi: '丙午', monthGanZhi: '戊申', dayGanZhi: '丙午',
      sanChuan: [{ chu: '丑', zhong: '亥', mo: '酉' }],
    }),
    judgment: '太常临支，青龙入传，翻修大利。勾陈临支下神，注意地基问题。宜择吉日动工。',
    verification: '翻修后祖宅焕然一新，家运兴旺',
    keyPoints: JSON.stringify(['太常临支', '青龙入传', '勾陈临支下']),
    keTi: '元首',
    tags: JSON.stringify(['田宅', '翻修', '兴旺']),
    shenshaList: JSON.stringify(['太常', '青龙', '勾陈']),
    biFaList: JSON.stringify(['太常喜庆', '青龙入传']),
  },
  {
    source: '六壬捷录新解',
    question: '某人占当日见客户能否签约',
    askTime: '丁未日辰时',
    eventType: '合作',
    lessonData: JSON.stringify({
      yearGanZhi: '丁未', monthGanZhi: '己酉', dayGanZhi: '丁未',
      sanChuan: [{ chu: '酉', zhong: '未', mo: '巳' }],
    }),
    judgment: '六合临三传，签约可成。青龙临日干，对方诚意足。干支上神相合，双方一拍即合。今日必成。',
    verification: '当日顺利签约',
    keyPoints: JSON.stringify(['六合临传', '青龙临干', '干支相合']),
    keTi: '元首',
    tags: JSON.stringify(['合作', '签约', '当日']),
    shenshaList: JSON.stringify(['六合', '青龙']),
    biFaList: JSON.stringify(['干支相会', '青龙入传']),
  },
  {
    source: '六壬捷录新解',
    question: '某人占老板是否会给涨薪',
    askTime: '戊申日午时',
    eventType: '求财',
    lessonData: JSON.stringify({
      yearGanZhi: '戊申', monthGanZhi: '庚戌', dayGanZhi: '戊申',
      sanChuan: [{ chu: '巳', zhong: '卯', mo: '丑' }],
    }),
    judgment: '青龙临日干，涨薪有望。贵人临三传，老板赏识。德禄临身，待遇提升。宜在月底提。',
    verification: '月底提涨薪，获批涨30%',
    keyPoints: JSON.stringify(['青龙临干', '贵人临传', '德禄临身']),
    keTi: '铸印',
    tags: JSON.stringify(['求财', '涨薪', '30%']),
    shenshaList: JSON.stringify(['青龙', '贵人']),
    biFaList: JSON.stringify(['青龙入传', '贵人临身', '德禄临身']),
  },
  {
    source: '六壬捷录新解',
    question: '某人占朋友借钱是否该借',
    askTime: '己酉日申时',
    eventType: '求财',
    lessonData: JSON.stringify({
      yearGanZhi: '己酉', monthGanZhi: '辛亥', dayGanZhi: '己酉',
      sanChuan: [{ chu: '亥', zhong: '丑', mo: '卯' }],
    }),
    judgment: '玄武临支上神（支为朋友），对方可能有隐情。天空临财星，借钱如投空。建议婉拒。',
    verification: '婉拒后得知该朋友欠债累累',
    keyPoints: JSON.stringify(['玄武临支', '天空临财']),
    keTi: '重审',
    tags: JSON.stringify(['求财', '借钱', '婉拒']),
    shenshaList: JSON.stringify(['玄武', '天空']),
    biFaList: JSON.stringify(['玄武入课', '天空无成']),
  },
  {
    source: '六壬捷录新解',
    question: '某人占航班是否会延误',
    askTime: '庚戌日寅时',
    eventType: '出行',
    lessonData: JSON.stringify({
      yearGanZhi: '庚戌', monthGanZhi: '壬子', dayGanZhi: '庚戌',
      sanChuan: [{ chu: '申', zhong: '午', mo: '辰' }],
    }),
    judgment: '驿马发动临干，出行必行。但天空临驿马，航班有变。朱雀临三传，注意查看通知。建议提前到机场。',
    verification: '航班延误三小时，但最终成行',
    keyPoints: JSON.stringify(['驿马发动', '天空临驿马', '朱雀临传']),
    keTi: '元首',
    tags: JSON.stringify(['出行', '航班', '延误']),
    shenshaList: JSON.stringify(['驿马', '天空', '朱雀']),
    biFaList: JSON.stringify(['驿马发动']),
  },
  {
    source: '六壬捷录新解',
    question: '某人占宠物狗走失能否找回',
    askTime: '辛亥日戌时',
    eventType: '失物',
    lessonData: JSON.stringify({
      yearGanZhi: '辛亥', monthGanZhi: '癸丑', dayGanZhi: '辛亥',
      sanChuan: [{ chu: '戌', zhong: '申', mo: '午' }],
    }),
    judgment: '玄武不临日干，非被盗。支上见六合临贵人，有好心人收留。初传在戌（西北），狗在西北方向。速去找。',
    verification: '在西北方某小区找到，被好心人收留',
    keyPoints: JSON.stringify(['玄武不临', '六合贵人', '初传戌']),
    keTi: '元首',
    tags: JSON.stringify(['失物', '宠物', '找到']),
    shenshaList: JSON.stringify(['六合', '贵人']),
    biFaList: JSON.stringify(['贵人临身']),
  },
  {
    source: '六壬捷录新解',
    question: '某人占买车时机',
    askTime: '壬子日巳时',
    eventType: '求财',
    lessonData: JSON.stringify({
      yearGanZhi: '壬子', monthGanZhi: '甲寅', dayGanZhi: '壬子',
      sanChuan: [{ chu: '卯', zhong: '丑', mo: '亥' }],
    }),
    judgment: '青龙临日干，购车时机成熟。驿马临三传，出行需求迫切。青龙临卯（卯为车），本月购车有利。',
    verification: '当月购车，驾驶体验良好',
    keyPoints: JSON.stringify(['青龙临干', '驿马临传', '青龙临卯']),
    keTi: '元首',
    tags: JSON.stringify(['求财', '购车', '有利']),
    shenshaList: JSON.stringify(['青龙', '驿马']),
    biFaList: JSON.stringify(['青龙入传', '驿马发动']),
  },
  {
    source: '六壬捷录新解',
    question: '某人占春节回老家路上安全',
    askTime: '癸丑日寅时',
    eventType: '出行',
    lessonData: JSON.stringify({
      yearGanZhi: '癸丑', monthGanZhi: '乙卯', dayGanZhi: '癸丑',
      sanChuan: [{ chu: '寅', zhong: '子', mo: '戌' }],
    }),
    judgment: '驿马青龙俱现，出行顺利。白虎不见，安全无虞。青龙临驿马，路上有贵人相助。安心出行。',
    verification: '一路平安，顺利到家',
    keyPoints: JSON.stringify(['驿马', '青龙', '白虎不见']),
    keTi: '元首',
    tags: JSON.stringify(['出行', '春节', '平安']),
    shenshaList: JSON.stringify(['驿马', '青龙']),
    biFaList: JSON.stringify(['驿马发动', '青龙入传']),
  },
  {
    source: '六壬捷录新解',
    question: '某人占被裁员后补偿谈判',
    askTime: '甲寅日申时',
    eventType: '官非',
    lessonData: JSON.stringify({
      yearGanZhi: '甲寅', monthGanZhi: '丙辰', dayGanZhi: '甲寅',
      sanChuan: [{ chu: '亥', zhong: '丑', mo: '卯' }],
    }),
    judgment: '朱雀临干，谈判有利。贵人临三传，仲裁可期。勾陈生日干，公司态度尚可。补偿可达N+3。',
    verification: '谈判成功，获N+3补偿',
    keyPoints: JSON.stringify(['朱雀临干', '贵人临传', '勾陈生干']),
    keTi: '知一',
    tags: JSON.stringify(['官非', '裁员', '补偿']),
    shenshaList: JSON.stringify(['朱雀', '贵人', '勾陈']),
    biFaList: JSON.stringify(['朱雀临门', '贵人临身']),
  },
  {
    source: '六壬捷录新解',
    question: '某人占出租房屋给谁为宜',
    askTime: '乙卯日巳时',
    eventType: '田宅',
    lessonData: JSON.stringify({
      yearGanZhi: '乙卯', monthGanZhi: '丁巳', dayGanZhi: '乙卯',
      sanChuan: [{ chu: '未', zhong: '巳', mo: '卯' }],
    }),
    judgment: '太常临支，出租顺利。六合临三传，租客诚信。青龙临末传，长期租赁有利。宜租给家庭用户。',
    verification: '租给一家人，三年无纠纷',
    keyPoints: JSON.stringify(['太常临支', '六合临传', '青龙末传']),
    keTi: '元首',
    tags: JSON.stringify(['田宅', '出租', '家庭']),
    shenshaList: JSON.stringify(['太常', '六合', '青龙']),
    biFaList: JSON.stringify(['太常喜庆', '青龙入传']),
  },
  {
    source: '大六壬推命学手抄本',
    question: '某人占一生财运格局（推命）',
    askTime: '丙辰日午时',
    eventType: '求财',
    lessonData: JSON.stringify({
      method: 'tui_ming',
      mingGong: '寅', shenGong: '午',
      mingGongShen: '青龙', shenGongShen: '太常',
    }),
    judgment: '命宫青龙临寅，一生财运亨通。身宫太常临午，宜礼仪、文化行业。大运顺排，中年财运最旺。',
    verification: '此人一生从事文化行业，中年致富',
    keyPoints: JSON.stringify(['命宫青龙', '身宫太常', '中年财运']),
    keTi: '元首',
    tags: JSON.stringify(['求财', '推命', '文化']),
    shenshaList: JSON.stringify(['青龙', '太常']),
    biFaList: JSON.stringify(['青龙入传', '太常喜庆']),
  },
  {
    source: '大六壬推命学手抄本',
    question: '某人占一生婚姻格局（推命）',
    askTime: '丁巳日酉时',
    eventType: '婚姻',
    lessonData: JSON.stringify({
      method: 'tui_ming',
      mingGong: '酉', shenGong: '丑',
      mingGongShen: '天后', shenGongShen: '六合',
    }),
    judgment: '命宫天后临酉，婚姻美满。身宫六合临丑，人缘极佳。终身课体三合课，夫妻恩爱白头。',
    verification: '此人一生婚姻幸福，子女双全',
    keyPoints: JSON.stringify(['命宫天后', '身宫六合', '三合课']),
    keTi: '三合',
    tags: JSON.stringify(['婚姻', '推命', '幸福']),
    shenshaList: JSON.stringify(['天后', '六合']),
    biFaList: JSON.stringify(['天后临日']),
  },
  {
    source: '大六壬推命学手抄本',
    question: '某人占一生事业格局（推命）',
    askTime: '戊午日辰时',
    eventType: '考试',
    lessonData: JSON.stringify({
      method: 'tui_ming',
      mingGong: '辰', shenGong: '申',
      mingGongShen: '贵人', shenGongShen: '朱雀',
    }),
    judgment: '命宫贵人临辰，一生有贵人相助。身宫朱雀临申，宜文职、法律行业。铸印课终身，仕途顺遂。',
    verification: '此人官至厅级',
    keyPoints: JSON.stringify(['命宫贵人', '身宫朱雀', '铸印课']),
    keTi: '铸印',
    tags: JSON.stringify(['考试', '推命', '仕途']),
    shenshaList: JSON.stringify(['贵人', '朱雀']),
    biFaList: JSON.stringify(['贵人临身', '朱雀临门']),
  },
  {
    source: '大六壬择日精要',
    question: '择某月嫁娶吉日',
    askTime: '择日',
    eventType: '婚姻',
    lessonData: JSON.stringify({
      method: 'ze_ri',
      eventType: '嫁娶',
      suitableDate: '甲子日',
      reason: '天后临日，六合临传，青龙临干，三合课成',
    }),
    judgment: '本月甲子日为嫁娶上吉。天后六合青龙俱临，三合课成，百年好合。宜辰时行礼。',
    verification: '当日成婚，婚后美满',
    keyPoints: JSON.stringify(['天后', '六合', '青龙', '三合课']),
    keTi: '三合',
    tags: JSON.stringify(['婚姻', '择日', '嫁娶']),
    shenshaList: JSON.stringify(['天后', '六合', '青龙']),
    biFaList: JSON.stringify(['天后临日', '青龙入传']),
  },
  {
    source: '大六壬择日精要',
    question: '择某月入宅吉日',
    askTime: '择日',
    eventType: '田宅',
    lessonData: JSON.stringify({
      method: 'ze_ri',
      eventType: '入宅',
      suitableDate: '丙寅日',
      reason: '太常临支，青龙临传，稼穑课成，德禄临身',
    }),
    judgment: '本月丙寅日为入宅上吉。太常青龙俱临，稼穑课成，入宅后家运兴旺。宜巳时入宅。',
    verification: '当日入宅，家运日隆',
    keyPoints: JSON.stringify(['太常', '青龙', '稼穑课', '德禄临身']),
    keTi: '稼穑',
    tags: JSON.stringify(['田宅', '择日', '入宅']),
    shenshaList: JSON.stringify(['太常', '青龙']),
    biFaList: JSON.stringify(['太常喜庆', '青龙入传', '德禄临身']),
  },
  {
    source: '大六壬择日精要',
    question: '择某月开业吉日',
    askTime: '择日',
    eventType: '求财',
    lessonData: JSON.stringify({
      method: 'ze_ri',
      eventType: '开业',
      suitableDate: '戊辰日',
      reason: '青龙临干，贵人临传，铸印课成，三传递生',
    }),
    judgment: '本月戊辰日为开业上吉。青龙贵人俱临，铸印课成，开业大吉大利。宜辰时开张。',
    verification: '当日开业，生意兴隆',
    keyPoints: JSON.stringify(['青龙', '贵人', '铸印课', '三传递生']),
    keTi: '铸印',
    tags: JSON.stringify(['求财', '择日', '开业']),
    shenshaList: JSON.stringify(['青龙', '贵人']),
    biFaList: JSON.stringify(['青龙入传', '贵人临身', '三传递生']),
  },
  {
    source: '大六壬择日精要',
    question: '择某月出行吉日',
    askTime: '择日',
    eventType: '出行',
    lessonData: JSON.stringify({
      method: 'ze_ri',
      eventType: '出行',
      suitableDate: '庚午日',
      reason: '驿马临干，青龙临传，轩盖课成，游子课兼见',
    }),
    judgment: '本月庚午日为出行上吉。驿马青龙俱临，轩盖课成，出行顺利大吉。宜寅时出发。',
    verification: '当日出行，一路顺风',
    keyPoints: JSON.stringify(['驿马', '青龙', '轩盖课', '游子课']),
    keTi: '轩盖',
    tags: JSON.stringify(['出行', '择日', '顺利']),
    shenshaList: JSON.stringify(['驿马', '青龙']),
    biFaList: JSON.stringify(['驿马发动', '青龙入传']),
  },
  {
    source: '大六壬高级预测学',
    question: '某人占是否适合转行做金融',
    askTime: '辛未日辰时',
    eventType: '求财',
    lessonData: JSON.stringify({
      yearGanZhi: '辛未', monthGanZhi: '癸酉', dayGanZhi: '辛未',
      sanChuan: [{ chu: '巳', zhong: '卯', mo: '丑' }],
    }),
    judgment: '青龙临日干，转行金融有利。但白虎临财星，金融风险大。铸印课成，宜传统金融而非投机。建议去银行。',
    verification: '转入银行工作，稳定发展',
    keyPoints: JSON.stringify(['青龙临干', '白虎临财', '铸印课']),
    keTi: '铸印',
    tags: JSON.stringify(['求财', '转行', '银行']),
    shenshaList: JSON.stringify(['青龙', '白虎']),
    biFaList: JSON.stringify(['青龙入传', '白虎入传']),
  },
  {
    source: '大六壬高级预测学',
    question: '某人占孩子早恋如何处理',
    askTime: '壬申日酉时',
    eventType: '婚姻',
    lessonData: JSON.stringify({
      yearGanZhi: '壬申', monthGanZhi: '甲戌', dayGanZhi: '壬申',
      sanChuan: [{ chu: '卯', zhong: '丑', mo: '亥' }],
    }),
    judgment: '天后临支（支为家），六合临三传，桃花正旺。八专课兼见，早恋属实。但朱雀临末传，沟通可解。宜耐心引导。',
    verification: '耐心沟通后，孩子专注学业',
    keyPoints: JSON.stringify(['天后临支', '六合临传', '八专课', '朱雀末传']),
    keTi: '八专',
    tags: JSON.stringify(['婚姻', '早恋', '沟通']),
    shenshaList: JSON.stringify(['天后', '六合', '朱雀']),
    biFaList: JSON.stringify(['天后临日']),
  },
  {
    source: '叶飘然大六壬讲义中',
    question: '某人占换房时机',
    askTime: '癸酉日巳时',
    eventType: '田宅',
    lessonData: JSON.stringify({
      yearGanZhi: '癸酉', monthGanZhi: '乙亥', dayGanZhi: '癸酉',
      sanChuan: [{ chu: '丑', zhong: '亥', mo: '酉' }],
    }),
    judgment: '太常临支，青龙入传，换房时机成熟。稼穑课成，新房风水上佳。但天空临末传，旧房出售需耐心。',
    verification: '换房成功，旧房三月后售出',
    keyPoints: JSON.stringify(['太常临支', '青龙入传', '稼穑课', '天空末传']),
    keTi: '稼穑',
    tags: JSON.stringify(['田宅', '换房', '成功']),
    shenshaList: JSON.stringify(['太常', '青龙', '天空']),
    biFaList: JSON.stringify(['太常喜庆', '青龙入传']),
  },
  {
    source: '叶飘然大六壬讲义中',
    question: '某人占公司裁员是否轮到自己',
    askTime: '甲戌日申时',
    eventType: '求财',
    lessonData: JSON.stringify({
      yearGanZhi: '甲戌', monthGanZhi: '丙子', dayGanZhi: '甲戌',
      sanChuan: [{ chu: '亥', zhong: '丑', mo: '卯' }],
    }),
    judgment: '贵人临日干，裁员轮不到自己。青龙临三传，反而可能有新机会。德禄临身，职位稳定。不必担心。',
    verification: '未在裁员名单中，反而接手了新项目',
    keyPoints: JSON.stringify(['贵人临干', '青龙临传', '德禄临身']),
    keTi: '知一',
    tags: JSON.stringify(['求财', '裁员', '安全']),
    shenshaList: JSON.stringify(['贵人', '青龙']),
    biFaList: JSON.stringify(['贵人临身', '青龙入传', '德禄临身']),
  },
  {
    source: '叶飘然大六壬讲义下',
    question: '某人占股票被套何时解套',
    askTime: '乙亥日午时',
    eventType: '求财',
    lessonData: JSON.stringify({
      yearGanZhi: '乙亥', monthGanZhi: '丁丑', dayGanZhi: '乙亥',
      sanChuan: [{ chu: '子', zhong: '戌', mo: '申' }],
    }),
    judgment: '青龙不临三传，近期难解套。天空临财星，账面浮亏。但末传见青龙在申，申月（农历七月）有望反弹。耐心持有。',
    verification: '农历七月股市反弹，成功解套',
    keyPoints: JSON.stringify(['青龙不临', '天空临财', '青龙在申']),
    keTi: '涉害',
    tags: JSON.stringify(['求财', '股票', '解套']),
    shenshaList: JSON.stringify(['青龙', '天空']),
    biFaList: JSON.stringify(['青龙入传', '天空无成']),
  },
  {
    source: '叶飘然大六壬讲义下',
    question: '某人占岳母对自己态度',
    askTime: '丙子日酉时',
    eventType: '合作',
    lessonData: JSON.stringify({
      yearGanZhi: '丙子', monthGanZhi: '戊寅', dayGanZhi: '丙子',
      sanChuan: [{ chu: '酉', zhong: '未', mo: '巳' }],
    }),
    judgment: '支上神（支为岳家）克干上神，岳母对己不满。太阴临支，岳母暗中挑剔。但六合临末传，终可化解。宜多送礼走动。',
    verification: '多走动送礼后，岳母态度明显改善',
    keyPoints: JSON.stringify(['支克干', '太阴临支', '六合末传']),
    keTi: '重审',
    tags: JSON.stringify(['合作', '岳母', '改善']),
    shenshaList: JSON.stringify(['太阴', '六合']),
    biFaList: JSON.stringify(['干支相克']),
  },
  {
    source: '叶飘然大六壬讲义下',
    question: '某人占孩子出国留学安全',
    askTime: '丁丑日寅时',
    eventType: '出行',
    lessonData: JSON.stringify({
      yearGanZhi: '丁丑', monthGanZhi: '己卯', dayGanZhi: '丁丑',
      sanChuan: [{ chu: '申', zhong: '午', mo: '辰' }],
    }),
    judgment: '驿马临支（支为子女），出国必行。青龙临三传，在外安全顺利。魁度天门，签证流程需耐心。但最终可成。',
    verification: '孩子顺利出国，留学期间一切平安',
    keyPoints: JSON.stringify(['驿马临支', '青龙临传', '魁度天门']),
    keTi: '元首',
    tags: JSON.stringify(['出行', '留学', '平安']),
    shenshaList: JSON.stringify(['驿马', '青龙']),
    biFaList: JSON.stringify(['驿马发动', '青龙入传', '魁度天门']),
  },
  {
    source: '叶飘然大六壬讲义下',
    question: '某人占自己是否有贵人运',
    askTime: '戊寅日辰时',
    eventType: '考试',
    lessonData: JSON.stringify({
      yearGanZhi: '戊寅', monthGanZhi: '庚辰', dayGanZhi: '戊寅',
      sanChuan: [{ chu: '巳', zhong: '卯', mo: '丑' }],
    }),
    judgment: '贵人临日干，青龙入传，六仪课成，贵人运极旺。三传递生，层层有人相助。一生多得贵人扶持。',
    verification: '此人一生遇事总有贵人相助',
    keyPoints: JSON.stringify(['贵人临干', '青龙入传', '六仪课', '三传递生']),
    keTi: '六仪',
    tags: JSON.stringify(['考试', '贵人运', '极旺']),
    shenshaList: JSON.stringify(['贵人', '青龙']),
    biFaList: JSON.stringify(['贵人临身', '青龙入传', '三传递生']),
  },
  {
    source: '六壬神课金口诀现代实例精解',
    question: '某人占当日谈客户能否成交（金口诀）',
    askTime: '己卯日巳时',
    eventType: '合作',
    lessonData: JSON.stringify({
      method: 'jin_kou_jue',
      diFen: '巳', yueJiang: '六合卯', guiShen: '青龙寅', renYuan: '丁',
      keTi: '将生干',
    }),
    judgment: '将生干，财来找人之象。青龙六合俱临，客户诚意足，成交在即。四位纯阳，明朗顺利。今日必成。',
    verification: '当日顺利签下大单',
    keyPoints: JSON.stringify(['将生干', '青龙临将', '六合临神', '四位纯阳']),
    keTi: '四位纯阳',
    tags: JSON.stringify(['合作', '签单', '金口诀']),
    shenshaList: JSON.stringify(['青龙', '六合']),
    biFaList: JSON.stringify([]),
  },
  {
    source: '六壬神课金口诀现代实例精解',
    question: '某人占考试能否及格（金口诀）',
    askTime: '庚辰日卯时',
    eventType: '考试',
    lessonData: JSON.stringify({
      method: 'jin_kou_jue',
      diFen: '卯', yueJiang: '朱雀午', guiShen: '天空戌', renYuan: '乙',
      keTi: '神克将',
    }),
    judgment: '神克将，天空克朱雀，考试发挥不佳。但将生地分，基础还在。及格边缘，需运气。建议多做准备。',
    verification: '勉强及格，60分飘过',
    keyPoints: JSON.stringify(['神克将', '天空克朱雀', '将生地分']),
    keTi: '神克将',
    tags: JSON.stringify(['考试', '及格', '金口诀']),
    shenshaList: JSON.stringify(['朱雀', '天空']),
    biFaList: JSON.stringify([]),
  },
  {
    source: '六壬神课金口诀现代实例精解',
    question: '某人占当日是否宜出门办事（金口诀）',
    askTime: '辛巳日午时',
    eventType: '出行',
    lessonData: JSON.stringify({
      method: 'jin_kou_jue',
      diFen: '午', yueJiang: '驿马寅', guiShen: '白虎申', renYuan: '丙',
      keTi: '神克将',
    }),
    judgment: '神克将，白虎克驿马，出行有阻。将克方，根基不稳。建议改日再办。今日不宜出行。',
    verification: '改日后出行，一切顺利',
    keyPoints: JSON.stringify(['神克将', '白虎克驿马', '将克方']),
    keTi: '神克将',
    tags: JSON.stringify(['出行', '不宜', '金口诀']),
    shenshaList: JSON.stringify(['白虎', '驿马']),
    biFaList: JSON.stringify([]),
  },
];

async function main() {
  console.log(`开始导入 ${cases.length} 条六壬断案案例...`);

  let inserted = 0;
  for (const c of cases) {
    await prisma.liurenCase.create({ data: c });
    inserted++;
    if (inserted % 20 === 0) {
      console.log(`已导入 ${inserted}/${cases.length} 条...`);
    }
  }

  const count = await prisma.liurenCase.count();
  console.log(`导入完成！数据库中共有 ${count} 条 LiurenCase 记录`);
}

main()
  .catch((e) => {
    console.error('导入失败:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });